### ISSUE TITLE
Is rsync install broken?

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#10066]
Rsync install fails when installing as a build dependency as mentioned in https://github.com/chromebrew/chromebrew/issues/10040#issuecomment-2197881703 : 
```
chronos@localhost / $ CREW_KERNEL_VERSION=6.6 crew reinstall -s linuxheaders
linuxheaders: Linux headers for Chrome OS.
Performing pre-flight checks...
The following packages also need to be installed: 
rsync
Do you agree? [Y/n] Y
Proceeding...
rsync: rsync is an open source utility that provides fast incremental file transfer.
Precompiled binary available, downloading...
Rsync archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
/usr/local/lib/ruby/3.3.0/fileutils.rb:1169:in `rename': No such file or directory @ rb_file_s_rename - (dlist, /usr/local/etc/crew/meta/rsync.directorylist) (Errno::ENOENT)
        from /usr/local/lib/ruby/3.3.0/fileutils.rb:1169:in `block in mv'
        from /usr/local/lib/ruby/3.3.0/fileutils.rb:2469:in `block in fu_each_src_dest'
        from /usr/local/lib/ruby/3.3.0/fileutils.rb:2485:in `fu_each_src_dest0'
        from /usr/local/lib/ruby/3.3.0/fileutils.rb:2467:in `fu_each_src_dest'
        from /usr/local/lib/ruby/3.3.0/fileutils.rb:1160:in `mv'
        from /usr/local/bin/crew:1047:in `block in install_package'
        from /usr/local/bin/crew:1043:in `chdir'
        from /usr/local/bin/crew:1043:in `install_package'
        from /usr/local/bin/crew:1272:in `install'
        from /usr/local/bin/crew:1208:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1205:in `each'
        from /usr/local/bin/crew:1205:in `resolve_dependencies'
        from /usr/local/bin/crew:1088:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1797:in `block in reinstall_command'
        from /usr/local/bin/crew:1787:in `each'
        from /usr/local/bin/crew:1787:in `reinstall_command'
        from /usr/local/bin/crew:1884:in `<main>'
```

> When I installed rsync manually via `crew install rsync` and tried the second time [it succeeded.]

**Comment by Zopolis4** [comment]
Perhaps this is a duplicate of #9820?
