### ISSUE TITLE
🐞 Building packages on arm is broken.

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#10081]
```
chronos@rpi51-armv7l /output/git/satmandu (mesa *)$ crew build -f packages/mesa.rb
/usr/local/lib/crew/lib/const.rb:174:in `<top (required)>': uninitialized constant CREW_ARCH_FLAGS (NameError)

CREW_CORE_FLAGS           = "-O2 -pipe -ffat-lto-objects -fPIC #{CREW_ARCH_FLAGS} -fuse-ld=#{CREW_LINKER} #{CREW_LINKER_FLAGS}"
                                                                 ^^^^^^^^^^^^^^^
Did you mean?  CREW_USE_CURL
        from /usr/local/lib/crew/commands/const.rb:1:in `require_relative'
        from /usr/local/lib/crew/commands/const.rb:1:in `<top (required)>'
        from /usr/local/bin/crew:15:in `require_relative'
        from /usr/local/bin/crew:15:in `<main>'
chronos@rpi51-armv7l /output/git/satmandu (mesa *)$
```

**Comment by satmandu** [comment]
We desperately need a GitHub action being run on armv7l to make sure these bugs are caught.

**Comment by Zopolis4** [comment]
I was not able to reproduce this... I am on the latest `arm32v7` container, digest `a3c1508f728a93cfb8858db22db1a35601530939e9432416b58dc9ac4f55e1e3`.

What setup are you using here?

**Comment by Zopolis4** [comment]
Shot in the dark-- try `export ARCH=armv7l`?

**Comment by satmandu** [comment]
This is the container I am using:
```bash
#!/bin/bash
if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
  SESSION_TYPE=remote/ssh
elif pstree -p | egrep --quiet --extended-regexp ".*sshd.*\($$\)"; then
  SESSION_TYPE=remote/ssh
else
  case $(ps -o comm= -p $PPID) in
    sshd|*/sshd) SESSION_TYPE=remote/ssh;;
  esac
fi
if [ -z ${PAGER+x} ]; then
  echo "PAGER is not set."
else
  PAGER_PASSTHROUGH=-e
  PAGER_PASSTHROUGH+=" "
  PAGER_PASSTHROUGH+=CONTAINER_PAGER=${PAGER}
fi
if [ -z ${TZ+x} ]; then
  echo "TZ is not set."
else
  TZ_PASSTHROUGH=-e
  TZ_PASSTHROUGH+=" "
  TZ_PASSTHROUGH+=TZ=${TZ}
fi
X11=-e
X11+=" "
X11+=DISPLAY=${DISPLAY:-:0.0}
X11+=" "
if ! [[ $SESSION_TYPE == remote/ssh ]] && [ -d /tmp/.X11-unix ]; then
  X11+=" -v /tmp/.X11-unix:/tmp/.X11-unix "
fi
if [ -f "$HOME"/.Xauthority ]; then
  X11+=--volume=$HOME/.Xauthority:/home/chronos/user/.Xauthority:rw
  X11+=" "
  X11+=--volume=$HOME/.Xauthority:/home/chronos/.Xauthority:rw                                                      fi                                                                                                                  docker pull --platform linux/arm/v7 satmandu/crewbuild:fievel-armv7l.m91
docker pull tonistiigi/binfmt
docker run --privileged --rm tonistiigi/binfmt --install all
docker run --init --platform linux/arm/v7 --rm --net=host ${PAGER_PASSTHROUGH} ${TZ_PASSTHROUGH} ${X11} -e LOCALRC="${LOCALRC}" -v $(pwd)/pkg_cache:/usr/local/tmp/packages -v $(pwd):/output -h $(hostname)-armv7l -it satmandu/crewbuild:fievel-armv7l.m91
```

**Comment by satmandu** [comment]
Then I do 
```
cd /output/path_to_cloned_git_repo
crew build -f packages/mesa.rb
```

**Comment by satmandu** [comment]
And yes `export ARCH=armv7l` does work around the error, but that shouldn't be necessary...

Also:
```bash
chronos@rpi51-armv7l /usr/local/lib/crew/packages (master >|SPARSE)$ crew const KERN_ARCH
/usr/local/lib/crew/lib/const.rb:174:in `<top (required)>': uninitialized constant CREW_ARCH_FLAGS (NameError)

CREW_CORE_FLAGS           = "-O2 -pipe -ffat-lto-objects -fPIC #{CREW_ARCH_FLAGS} -fuse-ld=#{CREW_LINKER} #{CREW_LINKER_FLAGS}"
                                                                 ^^^^^^^^^^^^^^^
Did you mean?  CREW_USE_CURL
        from /usr/local/lib/crew/commands/const.rb:1:in `require_relative'
        from /usr/local/lib/crew/commands/const.rb:1:in `<top (required)>'
        from /usr/local/bin/crew:15:in `require_relative'
        from /usr/local/bin/crew:15:in `<main>'
```

**Comment by Zopolis4** [comment]
It looks like you're running this on a raspberry pi-- presumably, that's reporting an architecture thats not `aarch64` or `armv7l`. You could use QEMU to ensure that you're running the correct architecture, which shouldn't be a meaningful speed penalty if youre on native arm hardware, or otherwise, you can export the ARCH variable manually to hide this.

**Comment by satmandu** [comment]
Qemu doesn't pass through the architecture. It would be much slower, and doing the big builds through there is a non-starter.

99% of the builds for armv7l ChromeOS are done on the Raspberry Pi because it is so much faster. (8Gb of ram, NVMe boot disk, etc...)

Please fix this regression. The workarounds in `const.rb` to handle `ARCH` when in these containers were there _for a reason._

**Comment by Zopolis4** [comment]
Adding `-e ARCH=armv7l` to your docker run command would fix this-- container workarounds, if possible, should be implemented in the containers themselves.

**Comment by satmandu** [comment]
Respectfully, we shouldn't have to use env variable overrides to just make the container work we do the majority of testing and building for an architecture on.

`crew` breaks on a major platform it is used on, which is these containers...

**Comment by Zopolis4** [comment]
I don't see the logic in having a workaround specific to your hardware in crew, especially when crew already has easy support for this workaround via an environment variable.

basically, here's what im thinking:
- if a workaround is needed for everyone (like aarch64 -> armv7l), it obviously makes sense to have it in crew
- if a workaround is needed for a specific usecase (i.e. running containers on a raspberry pi), it makes more sense to have it in whichever place that usecase is relevant

**Comment by satmandu** [comment]
```
chronos@rpi52-armv7l /usr/local/lib/crew/packages (master >|SPARSE)$ irb
irb(main):001> require 'etc'
=> false
irb(main):002> puts Etc.uname[:machine]
armv8l
=> nil
irb(main):003> 
```

**Comment by satmandu** [comment]
This is the fix:
```
# We report aarch64 & armv8l machines as armv7l for now, as we treat
# them as if they were armv7l.
# When we have proper aarch64 support, remove this.
# Also, we allow ARCH to be changed via the ARCH environment variable.
ARCH = ENV.fetch('ARCH') do |_name|
  case KERN_ARCH
  when 'aarch64', 'armv8l'
    'armv7l'
  else KERN_ARCH
  end
end
```

**Comment by uberhacker** [comment]
PR?
