### ISSUE TITLE
🐞 Bug Unable to update qt5_base

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#10088]
I tried to update qt5_base and ran into the following:
```
g++ -Wl,-O1 -Wl,--enable-new-dtags -Wl,--gc-sections -o ../../../bin/moc .obj/moc.o .obj/preprocessor.o .obj/generator.o .obj/parser.o .obj/token.o .obj/collectjson.o .obj/main.o   /usr/local/tmp/crew/qt5_base.20240706182725.dir/lib/libQt5Bootstrap.a -lz -lpthread   
/usr/local/bin/ld: /usr/local/lib64/gcc/x86_64-cros-linux-gnu/14/../../../../lib64/libstdc++.so: undefined reference to `strtof128'
/usr/local/bin/ld: /usr/local/lib64/gcc/x86_64-cros-linux-gnu/14/../../../../lib64/libstdc++.so: undefined reference to `strfromf128'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:145: ../../../bin/moc] Error 1
make[2]: Leaving directory '/usr/local/tmp/crew/qt5_base.20240706182725.dir/src/tools/moc'
make[1]: *** [Makefile:107: sub-moc-install_subtargets] Error 2
make[1]: Leaving directory '/usr/local/tmp/crew/qt5_base.20240706182725.dir/src'
make: *** [Makefile:63: sub-src-install_subtargets] Error 2
/usr/local/lib/crew/lib/package.rb:249:in `system': Command failed with exit 2: make (RuntimeError)
        from /usr/local/lib/crew/lib/package.rb:249:in `system'
        from /usr/local/lib/crew/packages/qt5_base.rb:105:in `install'
        from /usr/local/bin/crew:672:in `block in build_and_preconfigure'
        from /usr/local/bin/crew:644:in `chdir'
        from /usr/local/bin/crew:644:in `build_and_preconfigure'
        from /usr/local/bin/crew:1325:in `build_package'
        from /usr/local/bin/crew:1305:in `resolve_dependencies_and_build'
        from /usr/local/bin/crew:1671:in `block in build_command'
        from /usr/local/bin/crew:1653:in `each'
        from /usr/local/bin/crew:1653:in `build_command'
        from /usr/local/bin/crew:1884:in `<main>'
```
```
$ cat /etc/lsb-release 
CHROMEOS_ARC_ANDROID_SDK_VERSION=33
CHROMEOS_ARC_VERSION=11977712
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={95EE134E-B47F-43FB-9835-32C276865F9A}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={95EE134E-B47F-43FB-9835-32C276865F9A}
CHROMEOS_RELEASE_BOARD=hatch-signed-mp-v9keys
CHROMEOS_RELEASE_BRANCH_NUMBER=44
CHROMEOS_RELEASE_BUILDER_PATH=hatch-release/R126-15886.44.0
CHROMEOS_RELEASE_BUILD_NUMBER=15886
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=126
CHROMEOS_RELEASE_DESCRIPTION=15886.44.0 (Official Build) stable-channel hatch 
CHROMEOS_RELEASE_KEYSET=mp-v9
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_UNIBUILD=1
CHROMEOS_RELEASE_VERSION=15886.44.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=15886.44.0
```
```
$ crew const LIBC_VERSION
LIBC_VERSION=2.37
```
```
$ crew sysinfo
- Architecture: x86_64 (x86_64)
- Processor vendor: GenuineIntel
- User space: 64-bit
- Chromebrew Kernel version: 5.15
- Chromebrew Running in Container: false

- Chromebrew version: 1.49.4
- Chromebrew prefix: /usr/local
- Chromebrew libdir: /usr/local/lib64

- Last update in local repository: e0a1eeaf5 fix building armv7l binaries inside armv8l container regression (#10086) (2 days ago)

- OS variant: Chrome OS
- OS version: hatch-release/R126-15886.44.0
- OS channel: stable-channel
```

**Comment by Zopolis4** [comment]
I'm currently working on updating `qt5_base` on my branch `graceless`-- this is the `ld` issue again, and I was able to work around it in ed3850dc8c37a0926da79896c61fc4962209c8bd.

`arvm7l` builds still fail though, haven't figured those out yet.
