### ISSUE TITLE
🐞 Bug : docker cannot use overlay fs making it effectively useless 

### ISSUE THREAD

**Issue by apple-corps** [chromebrew/chromebrew#10139]
**Describe the bug**
docker cannot use overlay fs making it effectively useless 

Upon installing docker via crew

```
Performing post-install for fuse3...
sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
Command "bash -c sudo chown root:root /usr/local/bin/fusermount3" failed, retrying with "-j1"...
sudo: The "no new privileges" flag is set, which prevents sudo from running as root.
sudo: If sudo is running in a container, you may need to adjust the container configuration to disable the flag.
/usr/local/lib/crew/lib/package.rb:249:in `system': Command failed with exit 1: bash (RuntimeError)
        from /usr/local/lib/crew/lib/package.rb:249:in `system'
        from /usr/local/lib/crew/packages/fuse3.rb:40:in `postinstall'
        from /usr/local/bin/crew:704:in `block (2 levels) in post_install'
        from /usr/local/bin/crew:702:in `chdir'
        from /usr/local/bin/crew:702:in `block in post_install'
        from /usr/local/lib64/ruby/3.3.0/tmpdir.rb:99:in `mktmpdir'
        from /usr/local/bin/crew:701:in `post_install'
        from /usr/local/bin/crew:1095:in `block in resolve_dependencies_and_install'
        from /usr/local/bin/crew:1093:in `each'
        from /usr/local/bin/crew:1093:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1759:in `block in install_command'
        from /usr/local/bin/crew:1744:in `each'
        from /usr/local/bin/crew:1744:in `install_command'
        from /usr/local/bin/crew:1884:in `<main>'
```

After this I  manually ran the chown command above. It's not clear what other possible install or post install steps weren't completed successfully.

Then I tried to launch a container :

docker run --name some-postgis -e POSTGRES_PASSWORD=postgres postgis/postgis:16-3.4-alpine

The container images are pulled from the network. But we then get an error 

`fuse-overlayfs : cannot read lower dirs: Permission Denied .`

 Docker then returns exit code 1 when attempting to run a container.

**To Reproduce**

1. Please indicate where the command(s) were executed.

My environment was VT-2 :

2. I executed the command(s) below:
      ```shell
         crew install docker
         chown root:root /usr/local/bin/fusermount3
         docker run --name some-postgis -e POSTGRES_PASSWORD=postgres postgis/postgis:16-3.4-alpine
      ```

      Output:

      ```
      `fuse-overlayfs : cannot read lower dirs: Permission Denied .`
      ```
**Expected behavior**

**Screenshots**

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
***

**Additional context**

What I think needs to be done:

      - [ ] step one
      - [ ] step two

**Comment by Zopolis4** [comment]
Please fill out the system information field-- I think I might know what the issue is, but I can't tell without more information.

**Comment by apple-corps** [comment]
> crew sysinfo -v

crew sysinfo -v
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `6.6`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.49.3`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 7b4da5a72 `Terraform 1.9.0 => 1.9.1 (#10085) (4 weeks ago)`

- OS variant: `Chrome OS`
- OS version: `brya-release/R126-15886.44.0`
- OS channel: `stable-channel`

</details>

**Comment by apple-corps** [comment]
@Zopolis4  ^^

**Comment by Zopolis4** [comment]
Try installing and running `crew-sudo`, undoing ur manual modifications, and re-installing docker? Sudo doesn't work by default on the newer milestones, which might be the issue you're running into.

**Comment by satmandu** [comment]
You may only be able to use docker from crostini. AFAIK nested KVM is enabled for newer machines and the kernels on them, which is what you need to get that to work.

The problem with docker is that running without proper kernel access is a huge pain. Workarounds are kludgy at best.

Google appears to be shifting ChromeOS towards running under an Android kernel with nested kvm anyways, so that may be the way to go in any case moving forward, with docker running under another VM...

**Comment by satmandu** [comment]
We should probably mark the docker package as broken in some way, with a postinstall message to that effect...

**Comment by s0urce-c0de** [comment]
> Try installing and running `crew-sudo`, undoing ur manual modifications, and re-installing docker? Sudo doesn't work by default on the newer milestones, which might be the issue you're running into.

Disable rootfs verification and try https://gist.github.com/velzie/a5088c9ade6ec4d35435b9826b45d7a3
