### ISSUE TITLE
🐞 Bug gui apps seem to not work, sommelier also doesn't start correctly.

### ISSUE THREAD

**Issue by spaceguy47-2** [chromebrew/chromebrew#10158]
**Describe the bug**
Any apps that use gui either refuse to launch, or in the case of minecraft start to launch but crash before it shows anything.

**To Reproduce**

1. Please indicate where the command(s) were executed.

My environment was: crosh shell

2. I executed the command(s) below:
      ```shell
      # minecraft-launcher
      ```

      Output:

      ```
       [0715/105418.644560:ERROR:ozone_platform_x11.cc(234)] Missing X server or $DISPLAY
       [0715/105418.645606:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
       https://launchermeta.mojang.com/v1/products/launcher/6f083b80d5e6fabbc4236f81d0d8f8a350c665a9/linux.json
       OK
       OK
       [0715/105459.839358:ERROR:ozone_platform_x11.cc(234)] Missing X server or $DISPLAY
       [0715/105459.839580:ERROR:env.cc(225)] The platform failed to initialize.  Exiting.
      ```

3. I then tried:
      ```shell
      # restartsommelier
      ```

      Output:

      ```
       Sommelier can use direct scaling.
       Sommelier SCALE is set to .5.
       SCALE may be manually set in /usr/local/.config/.sommelier.env .
       some sommelier processes failed to start
       sommelier processes running:
         20642 /usr/local/bin/../lib64/ld-linux-x86-64.so.2 --library-path /usr/local/bin/../lib64 --inhibit-rpath  /usr/local/bin/sommelier.elf -X --x-display= --scale=.5 --direct-scale --glamor --force-drm-device=/dev/dri/renderD128 --display=wayland-0 --xwayland-path=/usr/local/bin/Xwayland --xwayland-gl-driver-path=/usr/local/lib64/dri --peer-cmd-prefix=/usr/local/lib64/ld-linux-x86-64.so.2 --noop-driver --no-exit-with-child /bin/sh -c xauth generate . trusted
      ```

**Expected behavior**
When I try to launch minecraft, it should succeed, and sommelier should fully start.

**System Information:**

***<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `4.19`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.49.6`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 040b7f658 `Freetube 0.21.0 => 0.21.1 (#10153) (16 hours ago)`

- OS variant: `Chrome OS`
- OS version: `caroline-release/R114-15437.42.0`
- OS channel: `stable-channel`

</details>***

sorry, Im pretty new to all this.

**Comment by uberhacker** [comment]
Try the following:
```
crew reinstall sommelier -s
restartsommelier
```

**Comment by spaceguy47-2** [comment]
didn't work

```
sommelier: Sommelier works by redirecting X11 programs to the built-in ChromeOS Exo Wayland server.
Performing pre-flight checks...
The following packages also need to be installed: 
llvm18_dev py3_markupsafe py3_jinja2
Do you agree? [Y/n] y
Proceeding...
llvm18_dev: LLVM: Everything except libLLVM & llvm-strip
Precompiled binary available, downloading...
Performing pre-install...
Performing install...
/usr/local/lib64/ruby/3.3.0/fileutils.rb:1169:in `rename': No such file or directory @ rb_file_s_rename - (dlist, /usr/local/etc/crew/meta/llvm18_dev.directorylist) (Errno::ENOENT)
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:1169:in `block in mv'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:2469:in `block in fu_each_src_dest'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:2485:in `fu_each_src_dest0'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:2467:in `fu_each_src_dest'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:1160:in `mv'
        from /usr/local/bin/crew:1046:in `block in install_package'
        from /usr/local/bin/crew:1042:in `chdir'
        from /usr/local/bin/crew:1042:in `install_package'
        from /usr/local/bin/crew:1271:in `install'
        from /usr/local/bin/crew:1207:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1204:in `each'
        from /usr/local/bin/crew:1204:in `resolve_dependencies'
        from /usr/local/bin/crew:1087:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1796:in `block in reinstall_command'
        from /usr/local/bin/crew:1786:in `each'
        from /usr/local/bin/crew:1786:in `reinstall_command'
        from /usr/local/bin/crew:1883:in `<main>'
sommelier stopped
Sommelier can use direct scaling.
Sommelier SCALE is set to .5.
SCALE may be manually set in /usr/local/.config/.sommelier.env .
some sommelier processes failed to start
sommelier processes running:  
 28485 /usr/local/bin/../lib64/ld-linux-x86-64.so.2 --library-path /usr/local/bin/../lib64 --inhibit-rpath  /usr/local/bin/sommelier.elf -X --x-display= --scale=.5 --direct-scale --glamor --force-drm-device=/dev/dri/renderD128 --display=wayland-0 --xwayland-path=/usr/local/bin/Xwayland --xwayland-gl-driver-path=/usr/local/lib64/dri --peer-cmd-prefix=/usr/local/lib64/ld-linux-x86-64.so.2 --noop-driver --no-exit-with-child /bin/sh -c xauth generate . trusted
```

**Comment by satmandu** [comment]
Try `yes | crew install llvm18_dev` first...

**Comment by spaceguy47-2** [comment]
still same issue, sommelier also still says that some processes failed to start.

**Comment by uberhacker** [comment]
What is the output of `tail /usr/local/var/log/sommelier.log`?

**Comment by uberhacker** [comment]
It appears you don't have a display set.  Does `echo $DISPLAY` output anything?  If not, try `export DISPLAY=:0` and `restartsommelier`.

**Comment by spaceguy47-2** [comment]
holy crap it worked, thank you so much.
