### ISSUE TITLE
🐞 [Bug] Unable to get prebuilt binary URL on older ChromeOS versions

### ISSUE THREAD

**Issue by supechicken** [chromebrew/chromebrew#10251]
**Describe the bug**
---
The new `get_binary_url(pkg)` function in #10152 does not work on older ChromeOS versions (one of my Chromebooks is on M84 and unable to do a clean install)

```
lzlib: Lzlib is a data compression library providing in-memory LZMA compression and decompression functions, including integrity checking of the decompressed data.
/usr/local/lib/ruby/3.3.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=172.65.251.78:443 state=error: certificate verify failed (self-signed certificate in certificate chain) (OpenSSL::SSL::SSLError)
        from /usr/local/lib/ruby/3.3.0/net/protocol.rb:46:in `ssl_socket_connect'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1674:in `connect'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1580:in `do_start'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1569:in `start'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1029:in `start'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:822:in `get_response'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:803:in `get'
        from /usr/local/lib/crew/lib/package_utils.rb:38:in `get_binary_url'
        from /usr/local/lib/crew/lib/package_utils.rb:17:in `get_url'
        from /usr/local/bin/crew:418:in `download'
        from /usr/local/bin/crew:1231:in `install'
        from /usr/local/bin/crew:1209:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1206:in `each'
        from /usr/local/bin/crew:1206:in `resolve_dependencies'
        from /usr/local/bin/crew:1089:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1760:in `block in install_command'
        from /usr/local/bin/crew:1745:in `each'
        from /usr/local/bin/crew:1745:in `install_command'
        from /usr/local/bin/crew:1885:in `<main>'
```

**Additional context**
---
- `cat /etc/lsb-release`
```
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={81C04B02-A863-BFBB-F77C-7707347DC958}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={81C04B02-A863-BFBB-F77C-7707347DC958}
CHROMEOS_RELEASE_BOARD=veyron_speedy-signed-mp-v3keys
CHROMEOS_RELEASE_BRANCH_NUMBER=110
CHROMEOS_RELEASE_BUILDER_PATH=veyron_speedy-release/R84-13099.110.0
CHROMEOS_RELEASE_BUILD_NUMBER=13099
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=84
CHROMEOS_RELEASE_DESCRIPTION=13099.110.0 (Official Build) stable-channel veyron_speedy 
CHROMEOS_RELEASE_KEYSET=mp-v3
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=13099.110.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=13099.110.0

```

**Comment by supechicken** [comment]
I didn't get any error with `curl` on the same system, weird...
```
$ /usr/bin/curl https://gitlab.com --verbose
*   Trying 2606:4700:90:0:f22e:fbec:5bed:a9b9:443...
* TCP_NODELAY set
* Connected to gitlab.com (2606:4700:90:0:f22e:fbec:5bed:a9b9) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=gitlab.com
*  start date: Apr 12 00:00:00 2024 GMT
*  expire date: May 11 23:59:59 2025 GMT
*  subjectAltName: host "gitlab.com" matched cert's "gitlab.com"
```

**Comment by VenomousSteam81** [comment]
I am getting that exact error but with glibc or glibc_lib when doing stuff with Ruby gems on m126.

**Comment by supechicken** [comment]
Update: This also affects my other ARM Chromebook on M125

**Comment by Zopolis4** [comment]
No idea what's going on there, hmm.

**Comment by Zopolis4** [comment]
a certificate error I might expect on a older system, but on M125? 

also, i'm only using ruby's net/http library, which has worked fine for downloading things...

Maybe we aren't installing ca_certificates early enough?

**Comment by supechicken** [comment]
We might need to specify the CA path for Net::HTTP as we did in `lib/downloader`:
https://github.com/chromebrew/chromebrew/blob/2249eee24e150d0e17b275a5d45397fce20947d0/lib/downloader.rb#L85-L92

Btw I am working on this...

**Comment by supechicken** [comment]
Hmm, seems `Net::HTTP.get` does not accept any extra options... We need another way of doing this.

**Comment by Zopolis4** [comment]
Is there a way to set the SSL path systemwide? Our current setup in `lib/const.rb` is pretty clunky anyways...

**Comment by Zopolis4** [comment]
Apparently it just looks like we need to set the environment variable `SSL_CERT_FILE` to `#{CREW_PREFIX}/etc/ssl/certs/ca-certificates.crt`?

**Comment by satmandu** [comment]
> Apparently it just looks like we need to set the environment variable `SSL_CERT_FILE` to `#{CREW_PREFIX}/etc/ssl/certs/ca-certificates.crt`?

Do you want to add a env.d file for ca_certificates to make sure that env variable exists?

**Comment by Zopolis4** [comment]
would something like that be better suited for crew-profile-base?

**Comment by Zopolis4** [comment]
see https://github.com/chromebrew/crew-profile-base/pull/27

**Comment by Zopolis4** [comment]
Try as I might, I'm unable to reproduce this issue in containers-- does this resolve the issue?
```
# in order to get back the broken code
CREW_REPO=https://github.com/Zopolis4/chromebrew.git CREW_BRANCH=ansc crew update

export SSL_CERT_DIR="${CREW_PREFIX}/etc/ssl/certs"
export SSL_CERT_FILE="${CREW_PREFIX}/etc/ssl/certs/ca-certificates.crt"
# try whatever command was failing before
crew install lzlib
```

**Comment by satmandu** [comment]
Does https://github.com/chromebrew/chromebrew/pull/10303 help?

**Comment by satmandu** [comment]
> would something like that be better suited for crew-profile-base?

As mentioned on the other PR, maybe we shouldn't have the env.d file set with a SSL variable before the cert file is installed.

**Comment by satmandu** [comment]
@supechicken please check to see if this issue is fixed now?

**Comment by supechicken** [comment]
It works now :)
