### ISSUE TITLE
🐞 Bug Unable to `crew update`

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#10350]
```
$ crew update
remote: Enumerating objects: 934, done.
remote: Counting objects: 100% (729/729), done.
remote: Compressing objects: 100% (261/261), done.
remote: Total 934 (delta 544), reused 565 (delta 462), pack-reused 205 (from 1)
Receiving objects: 100% (934/934), 1.38 MiB | 116.00 KiB/s, done.
Resolving deltas: 100% (619/619), completed with 218 local objects.
From https://github.com/chromebrew/chromebrew
 * branch                master     -> FETCH_HEAD
Updating files: 100% (4474/4474), done.
HEAD is now at 36aaefd78 Handle use of version variable in gcc_lib when in install.sh. (#10348)
Package lists, crew, and library updated.
Restarting crew update since there is an updated crew version.
From https://github.com/chromebrew/chromebrew
 * branch                master     -> FETCH_HEAD
HEAD is now at 36aaefd78 Handle use of version variable in gcc_lib when in install.sh. (#10348)
Package lists, crew, and library updated.
<internal:/usr/local/lib64/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require': cannot load such file -- highline/import (LoadError)
        from <internal:/usr/local/lib64/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /home/chronos/user/chromebrew/packages/ruby_pry.rb:2:in `load_package'
        from /usr/local/lib/crew/lib/package.rb:104:in `class_eval'
        from /usr/local/lib/crew/lib/package.rb:104:in `load_package'
        from /usr/local/bin/crew:175:in `set_package'
        from /usr/local/bin/crew:189:in `block in generate_compatible'
        from /usr/local/bin/crew:186:in `each'
        from /usr/local/bin/crew:186:in `generate_compatible'
        from /usr/local/bin/crew:294:in `update'
        from /usr/local/bin/crew:1807:in `update_command'
        from /usr/local/bin/crew:1846:in `<main>'
```

**Comment by Zopolis4** [comment]
also having this issue on some older containers of mine that i havent updated in a few weekrs-- `gem install highline` solves the issue, but i thought the point of all the code at the start of `bin/crew` and in `lib/fixup.rb` was to prevent the need for this...

**Comment by uberhacker** [comment]
> also having this issue on some older containers of mine that i havent updated in a few weekrs-- `gem install highline` solves the issue, but i thought the point of all the code at the start of `bin/crew` and in `lib/fixup.rb` was to prevent the need for this...

That is exactly the point of fixup.rb.  The problem is this was an oversight and never included in fixup.rb.
