### ISSUE TITLE
🐞 Bug Unable to `crew remove`

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#10352]
```
$ crew remove qt5_base
/usr/local/lib/crew/commands/remove.rb:64:in `split': invalid byte sequence in US-ASCII (ArgumentError)

          all_other_files = `grep -h --exclude #{[pkg.name](http://pkg.name/)}.filelist \"^#{CREW_PREFIX}\\|^#{HOME}\" #{CREW_META_PATH}/*.filelist`.split("\n").uniq.sort
                                                                                                                                       ^^^^
        from /usr/local/lib/crew/commands/remove.rb:64:in `block in remove'
        from /usr/local/lib/crew/commands/remove.rb:49:in `chdir'
        from /usr/local/lib/crew/commands/remove.rb:49:in `remove'
        from /usr/local/bin/crew:1765:in `block in remove_command'
        from /usr/local/bin/crew:1763:in `each'
        from /usr/local/bin/crew:1763:in `remove_command'
        from /usr/local/bin/crew:1846:in `<main>'
```

**Comment by satmandu** [comment]
Why is `#{[pkg.name](http://pkg.name/)}.filelist` happening?

**Comment by satmandu** [comment]
This is the relevant line 64:
```ruby
all_other_files = `grep -h --exclude #{pkg.name}.filelist \"^#{CREW_PREFIX}\\|^#{HOME}\" #{CREW_META_PATH}/*.filelist`.split("\n").uniq.sort
```

**Comment by satmandu** [comment]
I'm having trouble replicating this. In the hatch M126 container, I add and then remove qt5_base.

(I added a debug line to print what `pkg.name` is right before the relevant complaint.)

![Screenshot_20240825-101011.png](https://github.com/user-attachments/assets/3061fc93-faa9-49f3-a1c7-5982d18c942c)

**Comment by uberhacker** [comment]
Some more context.  This happens because I'm unable to `crew upgrade` due to qt5_base which depends on mysql.  Because mysql is not compatible with my glibc version, the whole process aborts.  And because I'm unable to remove qt5_base, I cannot continue with the updates.  Happens on more than one chromebook that requires updates.

**Comment by Zopolis4** [comment]
Working on mysql updates over at https://github.com/Zopolis4/chromebrew/tree/1really, but as CMake builds are currently broken not making much progress.

fwiw, @satmandu, I'm not sure what your build process is but it seems to frequently result in high minimum glibc values on packages that didn't have them before, which cuts off a lot of devices. are you confident that these are now the minimum required? I couldn't find anything in the mysql update notes saying anything about glibc changes, so I'm wondering if that really is the case.

**Comment by satmandu** [comment]
> Working on mysql updates over at https://github.com/Zopolis4/chromebrew/tree/1really, but as CMake builds are currently broken not making much progress.
> 
> fwiw, @satmandu, I'm not sure what your build process is but it seems to frequently result in high minimum glibc values on packages that didn't have them before, which cuts off a lot of devices. are you confident that these are now the minimum required? I couldn't find anything in the mysql update notes saying anything about glibc changes, so I'm wondering if that really is the case.

Streamer needs a higher glibc, and things that depend on that need to be built on that or higher.

I think if you got it to build on a lower glibc, you could build many other packages on a lower glibc.  But we need to prevent older glibc installs from bit rotting too.

FYI M121 was the last milestone not to use Glibc 2.37. (It uses Glibc 2.35)

**Comment by satmandu** [comment]
I believe this was fixed by https://github.com/chromebrew/chromebrew/pull/10363

**Comment by porteusconf** [comment]
For me `export LANG=en_US.UTF-8` got `crew remove` working, and got rid of `invalid byte sequence in US-ASCII (ArgumentError)` error. Full transcript showing how fix worked below...
```
Welcome to crosh, the ChromeOS developer shell.

If you got here by mistake, don't panic!  Just close this tab and carry on.

Type 'help' for a list of commands.

If you want to customize the look/behavior, you can use the options page.
Load it by using the Ctrl-Shift-P keyboard shortcut.

crosh> shell
chronos@reven / $ locale  ### Note env var LANG was unset for me ;-)
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
chronos@reven / $ crew install hello
hello: GNU Hello is another implementation of the classic program that prints “Hello, world!”
https://www.gnu.org/software/hello/
Version: 2.12
License: FDL-1.3 GPL-3
Performing pre-flight checks for hello...
Precompiled binary available, downloading...
Hello archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install for hello...
Performing install...
Hello installed!
chronos@reven / $ hello
Hello, world!
chronos@reven / $ crew remove hello
/usr/local/lib/crew/commands/remove.rb:68:in 'String#split': invalid byte sequence in US-ASCII (ArgumentError)

          all_other_files = `grep -h --exclude #{pkg.name}.filelist \"^#{CREW_PREFIX}\\|^#{HOME}\" #{CREW_META_PATH}/*.filelist 2>/dev/null`.split("\n").uniq.sort
                                                                                                                                                   ^^^^
        from /usr/local/lib/crew/commands/remove.rb:68:in 'block in Command.remove'
        from /usr/local/lib/crew/commands/remove.rb:52:in 'Dir.chdir'
        from /usr/local/lib/crew/commands/remove.rb:52:in 'Command.remove'
        from /usr/local/bin/crew:1847:in 'block in Object#remove_command'
        from /usr/local/bin/crew:1845:in 'Array#each'
        from /usr/local/bin/crew:1845:in 'Object#remove_command'
        from /usr/local/bin/crew:1901:in '<main>'
chronos@reven / $ 
chronos@reven / $ export LANG=en_US.UTF-8  ### <=== setting LANG fixed crew remove
chronos@reven / $ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
chronos@reven / $ crew remove hello
hello removed!
chronos@reven / $ crew sysinfo
- Architecture: x86_64 (x86_64)
- Processor vendor: AuthenticAMD
- User space: 64-bit
- Chromebrew Kernel version: 6.6
- Chromebrew Running in Container: false

- Chromebrew version: 1.57.2
- Chromebrew prefix: /usr/local
- Chromebrew libdir: /usr/local/lib64

- Last update in local repository: 69691ae4e Gradle 8.12.1 => 8.13 (#11447) (5 hours ago)

- OS variant: Chrome OS
- OS version: reven-release/R133-16151.53.0
- OS channel: stable-channel

$ date 
Mon Mar  3 05:37:11 -00 2025
```
