### ISSUE TITLE
🐞 crew whatprovides broken on arm.

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#10384]
```
chronos@rpi51-armv7l:2.27 M91 ~ $ crew whatprovides bin/convert
/usr/local/lib/crew/lib/package.rb:104:in `read': no implicit conversion of nil into String (TypeError)

    class_eval(File.read(pkg_file, encoding: Encoding::UTF_8), pkg_file) unless const_defined?("Package::#{class_name}")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /usr/local/lib/crew/lib/package.rb:104:in `load_package'
        from /usr/local/lib/crew/commands/whatprovides.rb:11:in `block in whatprovides'
        from /usr/local/lib/crew/commands/whatprovides.rb:7:in `each'
        from /usr/local/lib/crew/commands/whatprovides.rb:7:in `flat_map'
        from /usr/local/lib/crew/commands/whatprovides.rb:7:in `whatprovides'
        from /usr/local/bin/crew:1804:in `block in whatprovides_command'
        from /usr/local/bin/crew:1803:in `each'
        from /usr/local/bin/crew:1803:in `whatprovides_command'
        from /usr/local/bin/crew:1826:in `<main>'
chronos@rpi51-armv7l:2.27 M91 ~ $
```

**Comment by satmandu** [comment]
This is due to old manifest files without corresponding package files...  @Zopolis4  ideas for how to best deal with that?

**Comment by satmandu** [comment]
This is what I came up with:
```ruby
require_relative '../lib/const'
require_relative '../lib/package'
require_relative '../lib/package_utils'

class Command
  def self.whatprovides(regex)
    matched_list = `grep -R "#{regex}" #{CREW_LIB_PATH}/manifest/#{ARCH}`.lines(chomp: true).flat_map do |result|
      filelist, matched_file = result.split(':', 2)
      pkg_name = File.basename(filelist, '.filelist')
      pkg_name_status = File.file?(File.join(CREW_PACKAGES_PATH, "#{pkg_name}.rb")) ? pkg_name : nil
      if pkg_name_status
        if PackageUtils.compatible?(Package.load_package(File.join(CREW_PACKAGES_PATH, "#{pkg_name}.rb")))
          pkg_name_status = pkg_name.lightgreen if PackageUtils.installed?(pkg_name)
        else
          pkg_name_status = pkg_name.lightred
        end
      end

      pkg_name_status.nil? ? '' : "#{pkg_name_status}: #{matched_file}"
    end.sort.map(&:strip).reject(&:empty?)

    puts matched_list, "\nTotal found: #{matched_list.length}".lightgreen if matched_list.any?
  end
end
```
