### ISSUE TITLE
🐞 Can't install Rust correctly

### ISSUE THREAD

**Issue by antoine2711** [chromebrew/chromebrew#10552]
**Describe the bug**
Can't install rust.

**To Reproduce**

1. Please indicate where the command(s) were executed: `crew install rust`

2. My environment was: bash

3. Results
```shell
crew install rust
rust: Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety.
https://www.rust-lang.org/
Version: 1.81.0
License: Apache-2.0 and MIT
Performing pre-flight checks for rust...
Precompiled binary available, downloading...
Rust archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install for rust...
Performing install...
Using rdfind to convert duplicate files to hard links.
Now scanning ".", found 111 files.
Now have 111 files in total.
Removed 0 files due to nonunique device and inode.
Total size is 511986657 bytes or 488 MiB
Removed 103 files due to unique sizes from list. 8 files left.
Now eliminating candidates based on first bytes: removed 2 files from list. 6 files left.
Now eliminating candidates based on last bytes: removed 0 files from list. 6 files left.
Now eliminating candidates based on sha1 checksum: removed 0 files from list. 6 files left.
It seems like you have 6 files that are not unique
Totally, 13 MiB can be reduced.
Now making hard links.
Making 4 links.
Performing post-install for rust...
error: could not create home directory: '/home/chronos/user/.rustup': File exists (os error 17)
Command "bash -c rustup default stable" failed, retrying with "-j1"...
error: could not create home directory: '/home/chronos/user/.rustup': File exists (os error 17)
/usr/local/lib/crew/lib/package.rb:395:in `system': Command failed with exit 1: bash (RuntimeError)
        from /usr/local/lib/crew/lib/package.rb:395:in `system'
        from /usr/local/lib/crew/packages/rust.rb:82:in `postinstall'
        from /usr/local/bin/crew:750:in `block (2 levels) in post_install'
        from /usr/local/bin/crew:748:in `chdir'
        from /usr/local/bin/crew:748:in `block in post_install'
        from /usr/local/lib64/ruby/3.3.0/tmpdir.rb:99:in `mktmpdir'
        from /usr/local/bin/crew:747:in `post_install'
        from /usr/local/bin/crew:1129:in `block in resolve_dependencies_and_install'
        from /usr/local/bin/crew:1127:in `each'
        from /usr/local/bin/crew:1127:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1769:in `block in install_command'
        from /usr/local/bin/crew:1754:in `each'
        from /usr/local/bin/crew:1754:in `install_command'
        from /usr/local/bin/crew:1877:in `<main>'
```

**System Information**

<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `6.6`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.53.6`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 170218891 `Zoxide 0.9.4 => 0.9.6 (#10547) (8 hours ago)`

- OS variant: `Chrome OS`
- OS version: `brya-release/R128-15964.59.0`
- OS channel: `stable-channel`

</details>

**Comment by uberhacker** [comment]
It looks like you installed rust and uninstalled it without removing the local directory.  Try `rm -rf ~/.rustup` and `crew install rust`.

**Comment by antoine2711** [comment]
> It looks like you installed rust and uninstalled it without removing the local directory. Try `rm -rf ~/.rustup` and `crew install rust`.

@uberhacker:
I doubt this is the problem. First, I rarely uninstall software.

Second, I did a `reinstall` here, to try to fix it, and in the process, it told me that this file was being deleted.

```
["/home/chronos/user/.rustup", "/usr/local/share/rustup", "/home/chronos/user/.cargo", "/usr/local/share/cargo"] removed.
rust removed!
```

Regards, Antoine

**Comment by antoine2711** [comment]
> It looks like you installed rust and uninstalled it without removing the local directory. Try `rm -rf ~/.rustup` and `crew install rust`.

Didn’t work.

Regards, Antoine

**Comment by antoine2711** [comment]
v1.53.8 seams to fix the bug. Closing Issue.

Regards, Antoine
