### ISSUE TITLE
🐞 Bug | chromebrew is unable to open a TCP connection to gitlab.com:443

### ISSUE THREAD

**Issue by Eeeevox** [chromebrew/chromebrew#10762]
**Describe the bug**
After accepting to install dependencies or waiting about 3 seconds on the acceptence screen chromebrew complains about being unable to open a TCP conection to gitlab.com:443

**To Reproduce**
I dont know what i did, it insalled normaly before.

1. Please indicate where the command(s) were executed.
crew install [PACKAGE]

My environment was: crosh after running shell

2. I executed the command(s) below:
     as I said i dont know, it installed correctly before

      Output:

      ```
      /usr/local/lib/ruby/3.3.0/resolv-replace.rb:25:in `initialize': Failed to open TCP connection to gitlab.com:443 (Network is unreachable - connect(2) for "2606:4700:90:0:f22e:fbec:5bed:a9b9" port 443) (Errno::ENETUNREACH)
        from /usr/local/lib/ruby/3.3.0/resolv-replace.rb:25:in `initialize'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1603:in `open'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1603:in `block in connect'
        from /usr/local/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
        from /usr/local/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1601:in `connect'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1580:in `do_start'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1569:in `start'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1029:in `start'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:822:in `get_response'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:803:in `get'
        from /usr/local/lib/crew/lib/package_utils.rb:50:in `get_binary_url'
        from /usr/local/lib/crew/lib/package_utils.rb:27:in `get_url'
        from /usr/local/bin/crew:450:in `download'
        from /usr/local/bin/crew:1303:in `install'
        from /usr/local/bin/crew:1265:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1262:in `each'
        from /usr/local/bin/crew:1262:in `resolve_dependencies'
        from /usr/local/bin/crew:1154:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1865:in `block in reinstall_command'
        from /usr/local/bin/crew:1855:in `each'
        from /usr/local/bin/crew:1855:in `reinstall_command'
        from /usr/local/bin/crew:1934:in `<main>'
/usr/local/lib/ruby/3.3.0/resolv-replace.rb:25:in `initialize': Network is unreachable - connect(2) for "2606:4700:90:0:f22e:fbec:5bed:a9b9" port 443 (Errno::ENETUNREACH)
        from /usr/local/lib/ruby/3.3.0/resolv-replace.rb:25:in `initialize'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1603:in `open'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1603:in `block in connect'
        from /usr/local/lib/ruby/3.3.0/timeout.rb:186:in `block in timeout'
        from /usr/local/lib/ruby/3.3.0/timeout.rb:193:in `timeout'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1601:in `connect'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1580:in `do_start'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1569:in `start'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:1029:in `start'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:822:in `get_response'
        from /usr/local/lib/ruby/3.3.0/net/http.rb:803:in `get'
        from /usr/local/lib/crew/lib/package_utils.rb:50:in `get_binary_url'
        from /usr/local/lib/crew/lib/package_utils.rb:27:in `get_url'
        from /usr/local/bin/crew:450:in `download'
        from /usr/local/bin/crew:1303:in `install'
        from /usr/local/bin/crew:1265:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1262:in `each'
        from /usr/local/bin/crew:1262:in `resolve_dependencies'
        from /usr/local/bin/crew:1154:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1865:in `block in reinstall_command'
        from /usr/local/bin/crew:1855:in `each'
        from /usr/local/bin/crew:1855:in `reinstall_command'
        from /usr/local/bin/crew:1934:in `<main>'
      ```
**Expected behavior**
chromebrew procceds with the installation

**Screenshots**
![Image](https://github.com/user-attachments/assets/37ff97ec-5ccc-4ecd-bca2-96ff57100a47)
(happens independently of the package being installed)

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**

***
/usr/local/bin/crew:1931:<main>:The last update was 49 hrs, 53 min, 51 seconds ago.
<details><summary>Expand</summary>

- Architecture: `aarch64` (`armv7l`)
- Processor vendor: `ARM`
- User space: `64-bit`
- Chromebrew Kernel version: `6.6`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.55.9`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: 3171cf698 `Edge 130.0.2849.80-1 => 131.0.2903.48-1 (#10748) (3 days ago)`

- OS variant: `Chrome OS`
- OS version: `trogdor-release/R130-16033.58.0`
- OS channel: `stable-channel`

</details>
***

**Comment by satmandu** [comment]
Sounds like you have a network issue? Is IPv6 broken for you?

Try the tests at https://test-ipv6.com/

**Comment by Eeeevox** [comment]
@satmandu The test says i dont have an IPv6, but it worked before; do you know, perchance, how to fix it?

**Comment by satmandu** [comment]
Try rebooting. Your computer is trying to connect to Gitlab on IPv6, but it's failing because your IPv6 connectivity is broken.

**Comment by Eeeevox** [comment]
@satmandu i rebooted by pressing ctrl+reload (F3)+ power, but i still have no IPv6

**Comment by satmandu** [comment]
Yes but does the command work now?

**Comment by Eeeevox** [comment]
@satmandu no it doesnt

**Comment by Eeeevox** [comment]
@satmandu it seems like my internet provider has temporarily disabled IPv6 in the area for some reason, is there any way I can install things through IPv4?

**Comment by satmandu** [comment]
It should automatically fall back to ipv4. Maybe your DNS resolver is broken? Try changing DNS servers ...

**Comment by macg4dave** [comment]
I have the same error too,  My ISP does not support ipv6.  changing my dns server does not do anything too.

**Comment by porteusconf** [comment]
Me too: I am 3rd one it seems. Worked for months, even tho ISP does not provide ipv6, and did installs  ok earlier today. Then I did  `crew update && crew upgrade` today Sun Nov 24  2024 about 19:40:32 PM UTC, and  since that update, always fails to do any subsequent  installs or ownloads. always with same IPV6 related error. tho I can reach gitlab.com:443 by IP4 telnet ok:  
``` 
initialize: Failed to open TCP connection to gitlab.com:443 (Network is unreachable - connect(2) for "2606:4700:90:0:f22e:fbec:5bed:a9b9" port 443) (Errno::ENETUNREACH)
chronos@localhost / $ telnet gitlab.com 443
Trying 172.65.251.78...
Connected to gitlab.com.
Escape character is '^]'.
```
Like others, error persists after restarts, different  networks, change of dns, etc. Running on Intel HP chromebook-plus per below...

``` shell
chronos@localhost /usr/local/tmp $ crew update && crew upgrade
From https://github.com/chromebrew/chromebrew
 * branch                master     -> FETCH_HEAD
HEAD is now at 5d339d12c Vscodium 1.95.2.24313 => 1.95.3.24321 (#10787)
Package lists, crew, and library updated.
Checking for package updates...
Your software is up to date.
Your software is already up to date.
chronos@localhost /usr/local/tmp $ crew sysinfo
- Architecture: x86_64 (x86_64)
- Processor vendor: GenuineIntel
- User space: 64-bit
- Chromebrew Kernel version: 6.6
- Chromebrew Running in Container: false

- Chromebrew version: 1.56.0
- Chromebrew prefix: /usr/local
- Chromebrew libdir: /usr/local/lib64

- Last update in local repository: 5d339d12c Vscodium 1.95.2.24313 => 1.95.3.24321 (#10787) (26 hours ago)

- OS variant: Chrome OS
- OS version: nissa-release/R126-15886.69.0
- OS channel: stable-channel
chronos@localhost /usr/local/tmp $ date
Sun Nov 24 05:43:22 PM EST 2024
chronos@localhost /usr/local/tmp $ crew download  sqlitebrowser
sqlitebrowser: DB Browser for SQLite (DB4S) is a high quality, visual, open source tool to create, design, and edit database files compatible with SQLite
/usr/local/lib64/ruby/3.3.0/resolv-replace.rb:25:in`initialize': Failed to open TCP connection to gitlab.com:443 (Network is unreachable - connect(2) for "2606:4700:90:0:f22e:fbec:5bed:a9b9" port 443)  (Errno::ENETUNREACH)
        from /usr/local/lib64/ruby/3.3.0/resolv-replace.rb:25:in `initialize'
```

**Comment by satmandu** [comment]
Does this help at all?

```bash
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
```

**Comment by raydelto** [comment]
> Does this help at all?
> 
> sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
> sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
> sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1

This has worked for me! Thanks @satmandu !

**Comment by satmandu** [comment]
Please check if the new ruby 3.4.1 added yesterday solves this issue?

**Comment by porteusconf** [comment]
Yes, I am 99% sure ruby-3.4.1 fixed it (at least for me ;-)... I had the error from `crew install openvpn` before I did `crew upgrade ruby`, but with Ruby 3.4.1 and ipv6 NOT disabled, now `crew install openvpn` installed without needing the 3 work-around sudo lines. Thanks so much for chasing this down and more permanently resolving hopefully.

````
chronos@localhost / $ cat /proc/sys/net/ipv6/conf/all/disable_ipv6  ### 0 means ipv6 is *NOT* disabled
0
chronos@localhost / $ ruby --version
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +PRISM [x86_64-linux]
chronos@localhost / $ crew remove openvpn && crew install openvpn
 -> install matrix gem
Fetching matrix-0.4.2.gem
openvpn removed!
openvpn: OpenVPN is an open source VPN daemon
https://openvpn.net/
Version: 2.6.12
License: GPL-2
Performing pre-flight checks for openvpn...
Precompiled binary available, downloading...
Openvpn archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install for openvpn...
Performing install...
Using rdfind to convert duplicate files to hard links.
Now scanning ".", found 20 files.
Now have 20 files in total.
Removed 0 files due to nonunique device and inode.
Total size is 1074290 bytes or 1 MiB
Removed 20 files due to unique sizes from list. 0 files left.
Now eliminating candidates based on first bytes: removed 0 files from list. 0 files left.
Now eliminating candidates based on last bytes: removed 0 files from list. 0 files left.
Now eliminating candidates based on sha1 checksum: removed 0 files from list. 0 files left.
It seems like you have 0 files that are not unique
Totally, 0 B can be reduced.
Now making hard links.
Making 0 links.
Openvpn installed!
```
