### ISSUE TITLE
IPv6 connection failed

### ISSUE THREAD

**Issue by s0urce-c0de** [chromebrew/chromebrew#10795]
**Describe the bug**

**To Reproduce**

1. Please indicate where the command(s) were executed.

My environment was (crosh, bash or VT-2): crosh

2. I executed the command(s) below:
      ```shell
      Welcome to crosh, the ChromeOS developer shell.
      
      If you got here by mistake, don't panic!  Just close this tab and carry on.
      
      Type 'help' for a list of commands.
      
      If you want to customize the look/behavior, you can use the options page.
      Load it by using the Ctrl-Shift-P keyboard shortcut.
      
      crosh> shell
      chronos@localhost / $ crew install gcc
      gcc: The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, and Go.
      https://www.gnu.org/software/gcc/
      Version: 14.2.0-glibc2.37
      License: GPL-3, LGPL-3, libgcc, FDL-1.2
      Performing pre-flight checks for gcc...
      The following packages also need to be installed: 
      isl mpc gcc_dev
      Proceed (YES/no)?
      y
      isl: Integer Set Library for manipulating sets and relations of integer points bounded by linear constraints
      /usr/local/lib64/ruby/3.3.0/resolv-replace.rb:25:in `initialize': Failed to open TCP connection to gitlab.com:443 (Network is unreachable - connect(2) for "2606:4700:90:0:f22e:fbec:5bed:a9b9" port 443) (Errno::ENETUNREACH)
              from /usr/local/lib64/ruby/3.3.0/resolv-replace.rb:25:in `initialize'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1603:in `open'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1603:in `block in connect'
              from /usr/local/lib64/ruby/3.3.0/timeout.rb:186:in `block in timeout'
              from /usr/local/lib64/ruby/3.3.0/timeout.rb:193:in `timeout'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1601:in `connect'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1580:in `do_start'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1569:in `start'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1029:in `start'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:822:in `get_response'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:803:in `get'
              from /usr/local/lib/crew/lib/package_utils.rb:50:in `get_binary_url'
              from /usr/local/lib/crew/lib/package_utils.rb:27:in `get_url'
              from /usr/local/bin/crew:450:in `download'
              from /usr/local/bin/crew:1303:in `install'
              from /usr/local/bin/crew:1265:in `block in resolve_dependencies'
              from /usr/local/bin/crew:1262:in `each'
              from /usr/local/bin/crew:1262:in `resolve_dependencies'
              from /usr/local/bin/crew:1154:in `resolve_dependencies_and_install'
              from /usr/local/bin/crew:1826:in `block in install_command'
              from /usr/local/bin/crew:1811:in `each'
              from /usr/local/bin/crew:1811:in `install_command'
              from /usr/local/bin/crew:1934:in `<main>'
      /usr/local/lib64/ruby/3.3.0/resolv-replace.rb:25:in `initialize': Network is unreachable - connect(2) for "2606:4700:90:0:f22e:fbec:5bed:a9b9" port 443 (Errno::ENETUNREACH)
              from /usr/local/lib64/ruby/3.3.0/resolv-replace.rb:25:in `initialize'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1603:in `open'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1603:in `block in connect'
              from /usr/local/lib64/ruby/3.3.0/timeout.rb:186:in `block in timeout'
              from /usr/local/lib64/ruby/3.3.0/timeout.rb:193:in `timeout'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1601:in `connect'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1580:in `do_start'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1569:in `start'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:1029:in `start'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:822:in `get_response'
              from /usr/local/lib64/ruby/3.3.0/net/http.rb:803:in `get'
              from /usr/local/lib/crew/lib/package_utils.rb:50:in `get_binary_url'
              from /usr/local/lib/crew/lib/package_utils.rb:27:in `get_url'
              from /usr/local/bin/crew:450:in `download'
              from /usr/local/bin/crew:1303:in `install'
              from /usr/local/bin/crew:1265:in `block in resolve_dependencies'
              from /usr/local/bin/crew:1262:in `each'
              from /usr/local/bin/crew:1262:in `resolve_dependencies'
              from /usr/local/bin/crew:1154:in `resolve_dependencies_and_install'
              from /usr/local/bin/crew:1826:in `block in install_command'
              from /usr/local/bin/crew:1811:in `each'
              from /usr/local/bin/crew:1811:in `install_command'
              from /usr/local/bin/crew:1934:in `<main>'
      chronos@localhost / $ 
      ```
**Expected behavior**

I expected it to install GCC.

**Screenshots**

**System Information: Paste the output of `crew sysinfo -v` between the two `***` below.**
**If you cannot execute `crew`, display the output of `cat /etc/lsb-release` instead.**

***
/usr/local/bin/crew:1931:<main>:The last update was 8 seconds ago.
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `GenuineIntel`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.56.1`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: e5232edd3 `Update Repology JSON (#10788) (4 hours ago)`

- OS variant: `Chrome OS`
- OS version: `octopus-release/R130-16033.58.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**
Add any other context about the problem here. I am on a network with no IPv6 support, and I can use sudo in crosh due to https://gist.github.com/velzie/a5088c9ade6ec4d35435b9826b45d7a3, which I hope is not causing any conflicts.

What I think needs to be done:

      - [ ] Add an option to only use IPv4

**Comment by uberhacker** [comment]
What happens if you run `CREW_USE_CURL=1 crew install gcc`?

**Comment by s0urce-c0de** [comment]
> What happens if you run `CREW_USE_CURL=1 crew install gcc`?

It gives me the exact same error.

**Comment by s0urce-c0de** [comment]
![Image](https://github.com/user-attachments/assets/f09a2605-adb6-4ef3-a994-c55278325afa)

**Comment by j-ace-svg** [comment]
I've been getting the same error over the past few days. It appears that chromebooks don't have built-in support for DHCPv6, and only support IPv6 through SLACC and RDNSS (something configured on the network end). IPv4 seems to work fine, but I haven't found a way to make chromebrew use IPv4 instead of IPv6 yet.

**Comment by s0urce-c0de** [comment]
UPDATE: it suddenly works now after a restart, no update or anything. just crew update

**Comment by satmandu** [comment]
Mentioned more about why I think this is happening here: https://github.com/chromebrew/chromebrew/issues/10762#issuecomment-2506631212
