### ISSUE TITLE
🐞 cant install programs (again)

### ISSUE THREAD

**Issue by hexisXz** [chromebrew/chromebrew#10883]
Before i have used chromebrew to install programs like exa and htop but now after a fresh install I can no longer install anything even things that I know worked before

**To Reproduce**
crew install exa

1. Please indicate where the command(s) were executed.
tty and the shell in crosh

My environment was (crosh, bash or VT-2): tried both

2. I executed the command(s) below:
      ```shell
      crew install exa
      ```

      Output:
 
exa: Exa is a modern replacement for ls
https://the.exa.website/
Version: 0.10.1-1
License: Apache-2.0, MIT and Unlicense
Performing pre-flight checks for exa...
The following packages also need to be installed: 
libssh2 libgit2
Proceed (YES/no)?
y
libssh2: libssh2 is a client-side C library implementing the SSH2 protocol.
/usr/local/lib/ruby/3.3.0/resolv-replace.rb:25:in `initialize': Failed to open TCP connection to gitlab.com:443 (Network is unreachable - connect(2) for "2606:4700:90:0:f22e:fbec:5bed:a9b9" port 443) (Errno::ENETUNREACH)
        from /usr/local/lib/ruby/3.3.0/resolv-replace.rb:25:in `initialize'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1665:in `open'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1665:in `block in connect'
        from /usr/local/lib/ruby/gems/3.3.0/gems/timeout-0.4.2/lib/timeout.rb:183:in `block in timeout'
        from /usr/local/lib/ruby/gems/3.3.0/gems/timeout-0.4.2/lib/timeout.rb:190:in `timeout'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1663:in `connect'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1642:in `do_start'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1631:in `start'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1070:in `start'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:830:in `get_response'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:811:in `get'
        from /usr/local/lib/crew/lib/package_utils.rb:50:in `get_binary_url'
        from /usr/local/lib/crew/lib/package_utils.rb:27:in `get_url'
        from /usr/local/bin/crew:450:in `download'
        from /usr/local/bin/crew:1303:in `install'
        from /usr/local/bin/crew:1265:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1262:in `each'
        from /usr/local/bin/crew:1262:in `resolve_dependencies'
        from /usr/local/bin/crew:1154:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1826:in `block in install_command'
        from /usr/local/bin/crew:1811:in `each'
        from /usr/local/bin/crew:1811:in `install_command'
        from /usr/local/bin/crew:1934:in `<main>'
/usr/local/lib/ruby/3.3.0/resolv-replace.rb:25:in `initialize': Network is unreachable - connect(2) for "2606:4700:90:0:f22e:fbec:5bed:a9b9" port 443 (Errno::ENETUNREACH)
        from /usr/local/lib/ruby/3.3.0/resolv-replace.rb:25:in `initialize'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1665:in `open'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1665:in `block in connect'
        from /usr/local/lib/ruby/gems/3.3.0/gems/timeout-0.4.2/lib/timeout.rb:183:in `block in timeout'
        from /usr/local/lib/ruby/gems/3.3.0/gems/timeout-0.4.2/lib/timeout.rb:190:in `timeout'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1663:in `connect'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1642:in `do_start'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1631:in `start'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:1070:in `start'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:830:in `get_response'
        from /usr/local/lib/ruby/gems/3.3.0/gems/net-http-0.6.0/lib/net/http.rb:811:in `get'
        from /usr/local/lib/crew/lib/package_utils.rb:50:in `get_binary_url'
        from /usr/local/lib/crew/lib/package_utils.rb:27:in `get_url'
        from /usr/local/bin/crew:450:in `download'
        from /usr/local/bin/crew:1303:in `install'
        from /usr/local/bin/crew:1265:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1262:in `each'
        from /usr/local/bin/crew:1262:in `resolve_dependencies'
        from /usr/local/bin/crew:1154:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1826:in `block in install_command'
        from /usr/local/bin/crew:1811:in `each'
        from /usr/local/bin/crew:1811:in `install_command'
        from /usr/local/bin/crew:1934:in `<main>'

**Expected behavior**
exa was supposed to install (or any program I try to install not just exa)

**System Information: 

***
- Architecture: `aarch64` (`armv7l`)
- Processor vendor: `ARM`
- User space: `64-bit`
- Chromebrew Kernel version: `5.15`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.56.3`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: b4eb5e93e `Cabal 3.10.3.0 => 3.12.1.0 (#10867) (19 hours ago)`

- OS variant: `Chrome OS`
- OS version: `corsola-release/R130-16033.58.0`
- OS channel: `stable-channel`
***

***how can I fix this??***

**Comment by satmandu** [comment]
Pretty sure this is due to that recent change in the ruby `resolv` gem prioritizing using IPv6 hosts if they are resolved... Which in turn exposes a bug in ruby's net::http which doesn't retry connections to an IPv4 host if IPv6 connectivity to the Internet (as opposed to link-local/on the lan IPv6 connectivity) is broken.

**Comment by satmandu** [comment]
See https://github.com/chromebrew/chromebrew/issues/10762#issuecomment-2506631212

**Comment by hexisXz** [comment]
> See [#10762 (comment)](https://github.com/chromebrew/chromebrew/issues/10762#issuecomment-2506631212)

that worked for a bit but after installing a few apps I get this error now  

`/usr/local/lib/ruby/3.3.0/mkmf.rb:2717:in `expand_path': No such file or directory - getcwd (Errno::ENOENT)
        from /usr/local/lib/ruby/3.3.0/mkmf.rb:2717:in `<module:MakeMakefile>'
        from /usr/local/lib/ruby/3.3.0/mkmf.rb:46:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
        from /usr/local/bin/crew:31:in `<main>'`

**Comment by hexisXz** [comment]
> Pretty sure this is due to that recent change in the ruby `resolv` gem prioritizing using IPv6 hosts if they are resolved... Which in turn exposes a bug in ruby's net::http which doesn't retry connections to an IPv4 host if IPv6 connectivity to the Internet (as opposed to link-local/on the lan IPv6 connectivity) is broken.

is there a fix?

**Comment by satmandu** [comment]
> > Pretty sure this is due to that recent change in the ruby `resolv` gem prioritizing using IPv6 hosts if they are resolved... Which in turn exposes a bug in ruby's net::http which doesn't retry connections to an IPv4 host if IPv6 connectivity to the Internet (as opposed to link-local/on the lan IPv6 connectivity) is broken.
> 
> is there a fix?

Try this:

https://github.com/chromebrew/chromebrew/issues/10762#issuecomment-2496961321

**Comment by hexisXz** [comment]
> > > Pretty sure this is due to that recent change in the ruby `resolv` gem prioritizing using IPv6 hosts if they are resolved... Which in turn exposes a bug in ruby's net::http which doesn't retry connections to an IPv4 host if IPv6 connectivity to the Internet (as opposed to link-local/on the lan IPv6 connectivity) is broken.
> > 
> > 
> > is there a fix?
> 
> Try this workaround:
> 
> [#10762 (comment)](https://github.com/chromebrew/chromebrew/issues/10762#issuecomment-2496961321)

that' worked but now when I try to install crew-sudo I get this error similar to the other one

`Checking for conflicts of ruby_debug with files from installed packages...
/usr/local/bin/crew:1748:in `foreach': No such file or directory @ rb_sysopen - meta/ruby_debug.directorylist (Errno::ENOENT)
        from /usr/local/bin/crew:1748:in `block in remove'
        from /usr/local/bin/crew:1725:in `chdir'
        from /usr/local/bin/crew:1725:in `remove'
        from /usr/local/lib/crew/lib/fixup.rb:132:in `block in <top (required)>'
        from /usr/local/lib/crew/lib/fixup.rb:60:in `each'
        from /usr/local/lib/crew/lib/fixup.rb:60:in `<top (required)>'
        from /usr/local/bin/crew:654:in `load'
        from /usr/local/bin/crew:654:in `update'
        from /usr/local/bin/crew:2020:in `update_command'
        from /usr/local/bin/crew:2046:in `<main>'`

**Comment by satmandu** [comment]
Try those steps first, and then do a reinstall of Chromebrew and see if that helps?

**Comment by hexisXz** [comment]
> Try those steps first, and then do a reinstall of Chromebrew and see if that helps?

so that worked bunt now I cant launch graphical apps (this is kind of annoying) 

(epiphany:99320): libportal-CRITICAL **: 14:21:51.032: Failed to create XdpPortal instance: Error spawning command line ?dbus-launch --autolaunch=bd5619bf595ad54a86743684f489cb27 --binary-syntax --close-stderr?: Child process exited with code 1
