### ISSUE TITLE
Package request: ots

### ISSUE THREAD

**Issue by laerm0** [chromebrew/chromebrew#2642]
Hi all. I'm likely the only one here doing font development on chromeos, but, hey, `ots` is a useful package for anyone who wants to try to compile Firefox... 🤷‍♂️ 

[Github](https://github.com/khaledhosny/ots)

I can almost build it from source (using `meson`) but it calls an exe for some annoying reason. 😝 

Thanks for anyone who can figure this out. As I am not a programmer, don't count on me for anything other than encouragement and cheers.

**Comment by JL2210** [comment]
No, it doesn't. Try building it after running `sudo mount -o remount,rw,exec /tmp`.

**Comment by JL2210** [comment]
Give me the output of `crew list installed`, please. Is this a fresh `crew`?

**Comment by JL2210** [comment]
@uberhacker: I call this project.

**Comment by JL2210** [comment]
Great! I got an idea.

**Comment by JL2210** [comment]
Meson accepts TMPDIR, right?

**Comment by uberhacker** [comment]
What happens if you `rm /usr/local/bin/ld`?  If you get a `file not found` message, try starting a new crosh session.  You should then be able to default to `/usr/bin/ld`.

**Comment by JL2210** [comment]
Doesn't work. This is frustrating. I'll just switch to Clang for now.

**Comment by JL2210** [comment]
@laerm0: How is this for you? Does it work?
```ruby
require 'package'

class Ots < Package
  description 'The OpenType Sanitizer (OTS) parses and serializes OpenType files (OTF, TTF) and WOFF and WOFF2 font files, validating them and sanitiz$
  homepage 'https://github.com/khaledhosny/ots'
  version '7.1.7'
  source_url 'https://github.com/khaledhosny/ots/releases/download/v7.1.7/ots-7.1.7.tar.xz'
  source_sha256 '4cd2ab175b40363b5708d0246aa3acf65a21f5934879082c081502cf46675703'

  binary_url ({
  })
  binary_sha256 ({
  })

  depends_on 'meson' => :build
  depends_on 'ninja' => :build
  depends_on 'llvm' => :build
  depends_on 'freetype'

  def self.build
    system "TMPDIR='#{CREW_PREFIX}/tmp' CC='clang' CXX='clang++' LD='ld.lld' meson _build --prefix=#{CREW_PREFIX} --libdir=#{CREW_LIB_PREFIX}"
    system 'ninja', '-C', '_build'
  end

  def self.install
    system "ninja", "-C", "_build", "install", "DESTDIR=#{CREW_DEST_DIR}"
  end
end
```

**Comment by laerm0** [comment]
Hi there. Thanks to everyone for jumping on this. I am impressed with the quick work. :)

@JL2210 I'm afraid I don't know what to do with this... I will gladly test it out if you give me a little explanation.

**Comment by JL2210** [comment]
Open your favorite editor and paste it in, and then copy the file to /usr/local/lib/crew/packages/. Make sure to use `nano -w` if you use nano.

**Comment by laerm0** [comment]
Ah, thanks. I did so, then did `crew update` and `crew install ots` and got this error.

```chronos@localhost /usr/local/lib/crew/packages $ crew install ots
Traceback (most recent call last):
        13: from /usr/local/bin/crew:963:in `<main>'
        12: from /usr/local/bin/crew:905:in `install_command'
        11: from /usr/local/bin/crew:905:in `each'
        10: from /usr/local/bin/crew:907:in `block in install_command'
         9: from /usr/local/bin/crew:146:in `search'
         8: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `find'
         7: from /usr/local/lib64/ruby/2.5.0/find.rb:43:in `each'
         6: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `block in find'
         5: from /usr/local/lib64/ruby/2.5.0/find.rb:48:in `catch'
         4: from /usr/local/lib64/ruby/2.5.0/find.rb:49:in `block (2 levels) in find'
         3: from /usr/local/bin/crew:147:in `block in search'
         2: from /usr/local/bin/crew:108:in `set_package'
         1: from /usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib64/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': /usr/local/lib/crew/packages/ots.rb:5: syntax error, unexpected tIDENTIFIER, expecting keyword_end (SyntaxError)
    homepage 'https://github.com/khaledhosny/ots'
              ^~~~~
/usr/local/lib/crew/packages/ots.rb:5: unknown regexp options - gthb
/usr/local/lib/crew/packages/ots.rb:5: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
...s://github.com/khaledhosny/ots'
...                              ^
/usr/local/lib/crew/packages/ots.rb:6: unexpected fraction part after numeric literal
      version '7.1.7'
               ^~~
/usr/local/lib/crew/packages/ots.rb:6: syntax error, unexpected tFLOAT, expecting keyword_end
      version '7.1.7'
               ^~~~~~
```

**Comment by JL2210** [comment]
Give me the output of `cat /usr/local/lib/crew/packges/ots.rb`.

**Comment by JL2210** [comment]
Oh. Sorry. Stupid nano and its $ signs.

**Comment by JL2210** [comment]
```
require 'package'

class Ots < Package
  description 'The OpenType Sanitizer (OTS) parses and serializes OpenType files (OTF, TTF) and WOFF and WOFF2 font files, validating them and sanitizing them as it goes.'
  homepage 'https://github.com/khaledhosny/ots'
  version '7.1.7'
  source_url 'https://github.com/khaledhosny/ots/releases/download/v7.1.7/ots-7.1.7.tar.xz'
  source_sha256 '4cd2ab175b40363b5708d0246aa3acf65a21f5934879082c081502cf46675703'

  binary_url ({
  })
  binary_sha256 ({
  })

  depends_on 'meson' => :build
  depends_on 'ninja' => :build
  depends_on 'llvm' => :build
  depends_on 'freetype'

  def self.build
    system "TMPDIR='#{CREW_PREFIX}/tmp' CC='clang' CXX='clang++' LD='ld.lld' meson _build --prefix=#{CREW_PREFIX} --libdir=#{CREW_LIB_PREFIX}"
    system 'ninja', '-C', '_build'
  end

  def self.install
    system "ninja", "-C", "_build", "install", "DESTDIR=#{CREW_DEST_DIR}"
  end
end
```

**Comment by laerm0** [comment]
```require 'package'

class Ots < Package
  description 'The OpenType Sanitizer (OTS) parses and serializes OpenType files (OTF, TTF) and WOFF and WOFF2 font files, validating them and sanitiz$
    homepage 'https://github.com/khaledhosny/ots'
      version '7.1.7'
        source_url 'https://github.com/khaledhosny/ots/releases/download/v7.1.7/ots-7.1.7.tar.xz'
          source_sha256 '4cd2ab175b40363b5708d0246aa3acf65a21f5934879082c081502cf46675703'

            binary_url ({
              })
                binary_sha256 ({
                  })

                    depends_on 'meson' => :build
                      depends_on 'ninja' => :build
                        depends_on 'llvm' => :build
                          depends_on 'freetype'

                            def self.build
                                system "TMPDIR='#{CREW_PREFIX}/tmp' CC='clang' CXX='clang++' LD='ld.lld' meson _build --prefix=#{CREW_PREFIX} --libdir=#{CREW_LIB_PREFIX}"
                                    system 'ninja', '-C', '_build'
                                      end

                                        def self.install
                                            system "ninja", "-C", "_build", "install", "DESTDIR=#{CREW_DEST_DIR}"
                                              end
                                              end
```

**Comment by laerm0** [comment]
I'll try with your new text.

**Comment by laerm0** [comment]
Ahh, `meson` errors, which I get when I try to build it on my own (i.e. not via `crew`). I have [an issue open at the source](https://github.com/khaledhosny/ots/issues/174), so we will see if that can help.

```chronos@localhost /usr/local/lib/crew/packages $ crew install ots
ots: The OpenType Sanitizer (OTS) parses and serializes OpenType files (OTF, TTF) and WOFF and WOFF2 font files, validating them and sanitizing them as it goes.
https://github.com/khaledhosny/ots
version 7.1.7
No precompiled binary available for your platform, downloading source...
Archive downloaded
Unpacking archive, this may take awhile...
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Building from source, this may take a while...
Rename all *.la files to *.la_tmp
The Meson build system
Version: 0.47.1
Source dir: /usr/local/tmp/crew/ots-7.1.7.tar.xz.dir/ots-7.1.7
Build dir: /usr/local/tmp/crew/ots-7.1.7.tar.xz.dir/ots-7.1.7/_build
Build type: native build
Project name: ots
Project version: 7.1.7

meson.build:1:0: ERROR:  Compiler clang can not compile programs.

A full log can be found at /usr/local/tmp/crew/ots-7.1.7.tar.xz.dir/ots-7.1.7/_build/meson-logs/meson-log.txt
ots failed to install: `TMPDIR='/usr/local/tmp' CC='clang' CXX='clang++' LD='ld.lld' meson _build --prefix=/usr/local --libdir=/usr/local/lib64` exited with 1```

**Comment by JL2210** [comment]
You need to remount the /home older as exec. You need to do some more research before just randomly opening issues. Read the wiki.

**Comment by JL2210** [comment]
```
mount -o remount,rw -io exec ~/
```

**Comment by uberhacker** [comment]
@JL2210: I don't think we should be telling users to mount their home directory rwx.  The `xdg_base` package was created to eliminate the need to do this.  His TMPDIR is `/usr/local/tmp` so he shouldn't have any problem with executable files.  This looks like an issue with clang and not meson, actually.  @laerm0: What happens if you install Chromebrew fresh?
```
$ cp /usr/local/lib/crew/packages/ots.rb ~/
$ sudo rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
$ cp ~/ots.rb /usr/local/lib/crew/packages/
$ crew install ots
```

**Comment by laerm0** [comment]
Thanks @uberhacker (and apologies @JL2210). I have uninstalled and reinstalled chromebrew, reconfigured the filesystem as suggested, and I get an error with `clang`. 

```Building from source, this may take a while...
Rename all *.la files to *.la_tmp
The Meson build system
Version: 0.47.1
Source dir: /usr/local/tmp/crew/ots-7.1.7.tar.xz.dir/ots-7.1.7
Build dir: /usr/local/tmp/crew/ots-7.1.7.tar.xz.dir/ots-7.1.7/_build
Build type: native build
Project name: ots
Project version: 7.1.7

meson.build:1:0: ERROR:  Compiler clang can not compile programs.

A full log can be found at /usr/local/tmp/crew/ots-7.1.7.tar.xz.dir/ots-7.1.7/_build/meson-logs/meson-log.txt
ots failed to install: `TMPDIR='/usr/local/tmp' CC='clang' CXX='clang++' LD='ld.lld' meson _build --prefix=/usr/local --libdir=/usr/local/lib64` exited with 1
```

I'll put this on hold for now as I learn more. Thanks again for your help. Sorry to parachute in like a dummy. :)

**Comment by JL2210** [comment]
Can you give me the output of `clang`?

**Comment by laerm0** [comment]
`clang-6.0: error: no input files`

Looks like it works. 🤷‍♂️

**Comment by JL2210** [comment]
@laerm0: This may very well be possible without Clang when I fix the .relr.dyn issue. Stay tuned!

**Comment by JL2210** [comment]
@laerm0 I think I know why: The Clang update broke Clang. We can use `clc` now and fix the issue.
