### ISSUE TITLE
[metasploit] Unable to build

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#4411]
```
Downloading source...
######################################################################## 100.0%-#O#- #   #                                                           ######################################################################## 100.0%
Archive downloaded
Unpacking archive using 'tar', this may take a while...
Building from source, this may take a while...
Rename all *.la files to *.la_tmp
Successfully installed bundler-2.1.4
Parsing documentation for bundler-2.1.4
Installing ri documentation for bundler-2.1.4
Done installing documentation for bundler after 13 seconds
1 gem installed
/usr/local/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /usr/local/tmp/crew/6.0.9.tar.gz.dir/metasploit-framework-6.0.9/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
        from /usr/local/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
        from /usr/local/bin/bundle:23:in `<main>'
metasploit failed to build: `bundle install` exited with 1
```

**Comment by cstrouse** [comment]
So this is a problem with our Ruby package?

**Comment by uberhacker** [comment]
No, I think this package has to make sure the correct version of bundler is installed.  Probably just need to pin the version.

**Comment by cstrouse** [comment]
@uberhacker It could be related to the reorganization of the project repos ([see their announcement](https://bundler.io/blog/2020/04/27/march-monthly-update.html)). I added `bundle update --bundler` as the first build step command and just started the build again.

**Comment by cstrouse** [comment]
Ok, so that enabled me to build the metasploit package from source. I'll open a PR.
