### ISSUE TITLE
Unable to upgrade glibc on i686

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#6733]
```
Updating packages...
glibc: The GNU C Library project provides the core libraries for GNU/Linux systems.
Performing pre-flight checks...
Precompiled binary available, downloading...
<internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': libssl.so.1.1: cannot open shared object file: No such file or directory - /usr/local/lib/ruby/3.0.0/i686-linux-gnu/openssl.so (LoadError)
        from <internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/ruby/3.0.0/openssl.rb:13:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/ruby/3.0.0/net/http.rb:612:in `start'
        from /usr/local/lib/crew/lib/downloader.rb:55:in `downloader'
        from /usr/local/bin/crew:709:in `block in download'
        from /usr/local/bin/crew:675:in `chdir'
        from /usr/local/bin/crew:675:in `download'
        from /usr/local/bin/crew:1397:in `install'
        from /usr/local/bin/crew:1263:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:642:in `block in upgrade'
        from /usr/local/bin/crew:637:in `each'
        from /usr/local/bin/crew:637:in `upgrade'
        from /usr/local/bin/crew:1785:in `upgrade_command'
        from /usr/local/bin/crew:1801:in `<main>'
```

**Comment by satmandu** [comment]
Reopen if still an issue?
