### ISSUE TITLE
cant install nano 

### ISSUE THREAD

**Issue by Kalion2000** [chromebrew/chromebrew#7064]
If you executed a specific command:
```shell
crew install nano
```

Output:
```
nano: Nano's ANOther editor, an enhanced free Pico clone.
https://www.nano-editor.org/
Version: 6.1
License: GPL-3
Performing pre-flight checks...
The following packages also need to be installed: 
xdg_base
Do you agree? [Y/n] y
Proceeding...
xdg_base: XDG Base Directory Specification Configuration
Precompiled binary available, downloading...
[####################################################################################################################################]  524.00 B 100%
Xdg_base archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
<internal:dir>:98:in `open': Permission denied @ dir_initialize - /home/chronos/user/.config (Errno::EACCES)
        from /usr/local/lib64/ruby/3.1.0/fileutils.rb:1280:in `children'
        from /usr/local/lib64/ruby/3.1.0/fileutils.rb:1280:in `entries'
        from /usr/local/lib64/ruby/3.1.0/fileutils.rb:1495:in `wrap_traverse'
        from /usr/local/lib64/ruby/3.1.0/fileutils.rb:487:in `copy_entry'
        from /usr/local/lib64/ruby/3.1.0/fileutils.rb:461:in `block in cp_r'
        from /usr/local/lib64/ruby/3.1.0/fileutils.rb:1577:in `block in fu_each_src_dest'
        from /usr/local/lib64/ruby/3.1.0/fileutils.rb:1591:in `fu_each_src_dest0'
        from /usr/local/lib64/ruby/3.1.0/fileutils.rb:1575:in `fu_each_src_dest'
        from /usr/local/lib64/ruby/3.1.0/fileutils.rb:460:in `cp_r'
        from /usr/local/lib/crew/packages/xdg_base.rb:26:in `preinstall'
        from /usr/local/bin/crew:936:in `block in pre_install'
        from /usr/local/bin/crew:934:in `chdir'
        from /usr/local/bin/crew:934:in `pre_install'
        from /usr/local/bin/crew:1416:in `install'
        from /usr/local/bin/crew:1363:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1359:in `each'
        from /usr/local/bin/crew:1359:in `resolve_dependencies'
        from /usr/local/bin/crew:1294:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1781:in `block in install_command'
        from /usr/local/bin/crew:1776:in `each'
        from /usr/local/bin/crew:1776:in `install_command'
        from /usr/local/bin/crew:1898:in `<main>'
```

## Versions and system information
***
```
fatal: ambiguous argument 'HEAD^..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `4.19.229-12876-gf06fecba2685`

- Chromebrew version: `1.23.16`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: ``

- OS variant: `Chrome OS`
- OS version: `cyan-release/R100-14526.89.0`
- OS channel: `stable-channel`

***

**Comment by uberhacker** [comment]
The `xdg_base` package will install a symlink to `~/.config` from `/usr/local/.config`.

**Comment by satmandu** [comment]
Is this still an issue?

**Comment by satmandu** [comment]
Closing as missing user feedback...
