### ISSUE TITLE
i cant install crew: /usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `urandom': failed to get urandom (RuntimeError)

### ISSUE THREAD

**Issue by Fazilrahmantkn** [chromebrew/chromebrew#7205]
## Description

cant install crew. installing was almost full when i get this error from ruby
If you executed a specific command:
```shell
# your command here
```
  curl -Ls git.io/vddgY -o install.sh && yes | bash install.sh
Output:
```
# output of your command here
Welcome to Chromebrew!


Doing initial setup for install in /usr/local.
This may take a while if there are preexisting files in /usr/local...

Resetting ownership of /usr/local/bin
Resetting ownership of /usr/local/etc
Resetting ownership of /usr/local/include
Resetting ownership of /usr/local/lib
Resetting ownership of /usr/local/lib
Resetting ownership of /usr/local/libexec
Resetting ownership of /usr/local/share
Resetting ownership of /usr/local/tmp

Downloading information for Bootstrap packages...

[1/15]: https://raw.githubusercontent.com/chromebrew/chromebrew/master/packages/musl_zstd.rb --> musl_zstd.rb
--_curl_--https://raw.githubusercontent.com/chromebrew/chromebrew/master/packages/musl_zstd.rb
** Resuming transfer from byte position 2258
.....
gcc12-12.1-chromeos-armv7l.tar.zst: OK
Extracting gcc12 ...
Installing gcc12 ...
Updating version number of gcc12 in device.json...
Downloading rsync...
################################################################################################################################################ 100.0%
Verifying rsync...
rsync-3.2.4-1-chromeos-armv7l.tar.zst: OK
Extracting rsync ...
Installing rsync ...
Updating version number of rsync in device.json...
Downloading ruby...
################################################################################################################################################ 100.0%
Verifying ruby...
ruby-3.1.2-2-chromeos-armv7l.tar.zst: OK
Extracting ruby ...
Installing ruby ...
Updating version number of ruby in device.json...

Creating symlink to 'crew' in /usr/local/bin/
Setup and synchronize local package repo...

Cloning into '/usr/local/lib/crew'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 0), reused 4 (delta 0), pack-reused 0
Receiving objects: 100% (9/9), 52.64 KiB | 7.52 MiB/s, done.
remote: Enumerating objects: 1943, done.
remote: Counting objects: 100% (1943/1943), done.
remote: Compressing objects: 100% (1762/1762), done.
remote: Total 1943 (delta 216), reused 548 (delta 181), pack-reused 0
Receiving objects: 100% (1943/1943), 1.50 MiB | 211.00 KiB/s, done.
Resolving deltas: 100% (216/216), done.
Updating files: 100% (1943/1943), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at d40792a Brave 1.40.113 => 1.41.96 (#7204)

Updating crew package information...

/usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `urandom': failed to get urandom (RuntimeError)
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `singleton class'
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:42:in `<module:SecureRandom>'
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:41:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/ruby/3.1.0/resolv.rb:8:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/ruby/3.1.0/resolv-replace.rb:4:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/crew/lib/downloader.rb:21:in `<top (required)>'
        from /usr/local/bin/crew:15:in `require_relative'
        from /usr/local/bin/crew:15:in `<main>'
/usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `urandom': failed to get urandom (RuntimeError)
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:75:in `singleton class'
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:42:in `<module:SecureRandom>'
        from /usr/local/lib/ruby/3.1.0/securerandom.rb:41:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/ruby/3.1.0/resolv.rb:8:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/ruby/3.1.0/resolv-replace.rb:4:in `<top (required)>'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/local/lib/crew/lib/downloader.rb:21:in `<top (required)>'
        from /usr/local/bin/crew:15:in `require_relative'
        from /usr/local/bin/crew:15:in `<main>'
```

## Versions and system information

***
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={D851316B-7E57-4805-A7CE-01829AC1443E}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={D851316B-7E57-4805-A7CE-01829AC1443E}
CHROMEOS_RELEASE_BOARD=daisy-signed-mp-v4keys
CHROMEOS_RELEASE_BRANCH_NUMBER=100
CHROMEOS_RELEASE_BUILDER_PATH=daisy-release/R75-12105.100.0
CHROMEOS_RELEASE_BUILD_NUMBER=12105
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=75
CHROMEOS_RELEASE_DESCRIPTION=12105.100.0 (Official Build) stable-channel daisy 
CHROMEOS_RELEASE_KEYSET=mp-v4
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=12105.100.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=12105.100.0
***

**Comment by uberhacker** [comment]
@Fazilrahmantkn: This looks like an issue with a pre-existing install.  If you don't have anything you need to save in `/usr/local`, I would recommend the following:
```
$ rm -rf /usr/local
$ curl -Ls git.io/vddgY | bash
```
Always better to start with a clean slate.

**Comment by supechicken** [comment]
This error should be fixed now, could you try again with `crew update || crew update`?
