### ISSUE TITLE
`http_downloader': uninitialized constant Net (NameError)

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#7207]
```
py3_pyparsing: The pyparsing module is an alternative approach to creating and executing simple grammars, vs. the traditional lex/yacc approach, or the use of regular expressions.
Precompiled binary available, downloading...
/usr/local/lib/crew/lib/downloader.rb:90:in `http_downloader': uninitialized constant Net (NameError)

  Net::HTTP.start(uri.host, uri.port, {
  ^^^
	from /usr/local/lib/crew/lib/downloader.rb:61:in `downloader'
	from /usr/local/bin/crew:720:in `block in download'
	from /usr/local/bin/crew:688:in `chdir'
	from /usr/local/bin/crew:688:in `download'
	from /usr/local/bin/crew:1393:in `install'
	from /usr/local/bin/crew:1373:in `block in resolve_dependencies'
	from /usr/local/bin/crew:1369:in `each'
	from /usr/local/bin/crew:1369:in `resolve_dependencies'
	from /usr/local/bin/crew:1459:in `resolve_dependencies_and_build'
	from /usr/local/bin/crew:1729:in `block in build_command'
	from /usr/local/bin/crew:1725:in `each'
	from /usr/local/bin/crew:1725:in `build_command'
	from /usr/local/bin/crew:1908:in `<main>'
```

**Comment by n0w33d** [comment]
If you need to fix this issue on your own wile we all wait for the solution to merge, you will need to do the following steps:

1. vim or nano the following file: /usr/local/lib/crew/lib/downloader.rb
2. insert a new line at the top and add the following line:
3. require 'net/http'
4. save and attempt to update Crew and install something via `crew install` command
