### ISSUE TITLE
glibc postinstall breaks while installation

### ISSUE THREAD

**Issue by kunver400** [chromebrew/chromebrew#7330]
## Description

Install command
```shell
curl -Ls git.io/vddgY | bash
```

Output:
```
Performing post-install for glibc...
System glibc version is 2.33.
Creating symlinks to system glibc version to prevent breakage.
Paring locales to a minimal set.
/usr/local/lib/crew/packages/glibc.rb:627:in `readlines': No such file or directory @ rb_sysopen - /usr/local/etc/crew/meta/package::glibc.filelist (Errno::ENOENT)
        from /usr/local/lib/crew/packages/glibc.rb:627:in `postinstall'
        from /usr/local/bin/crew:935:in `block (2 levels) in post_install'
        from /usr/local/bin/crew:933:in `chdir'
        from /usr/local/bin/crew:933:in `block in post_install'
        from /usr/local/lib/ruby/3.1.0/tmpdir.rb:96:in `mktmpdir'
        from /usr/local/bin/crew:932:in `post_install'
        from /usr/local/bin/crew:1284:in `block in resolve_dependencies_and_install'
        from /usr/local/bin/crew:1282:in `each'
        from /usr/local/bin/crew:1282:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1756:in `block in install_command'
        from /usr/local/bin/crew:1751:in `each'
        from /usr/local/bin/crew:1751:in `install_command'
        from /usr/local/bin/crew:1875:in `<main>'
```

## Versions and system information

***
crew sysinfo
- Architecture: `aarch64` (`aarch64`)
- Kernel version: `5.10.120-16471-g167ad2e5dcba`

- Chromebrew version: `1.25.3`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib`

- Last update in local repository: 823ccee `libiconv -> 1.17 (#7326) (12 hours ago)`

- OS variant: `Chrome OS`
- OS version: `kukui-release/R104-14909.124.0`
- OS channel: `stable-channel`
***

**Comment by uberhacker** [comment]
@supechicken?

**Comment by satmandu** [comment]
This was fixed by https://github.com/chromebrew/chromebrew/pull/7340
