### ISSUE TITLE
nvim: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Metal-Toilet** [chromebrew/chromebrew#7367]
## Description

Error when trying to open neovim.

```shell
chronos@localhost / $ nvim
```

Output:
```
nvim: error while loading shared libraries: libiconv.so.2: cannot open shared object file: No such file or directory
```

## Versions and system information
***
Ignoring debug-1.4.0 because its extensions are not built. Try: gem pristine debug --version 1.4.0
- Architecture: `x86_64` (`x86_64`)
- Kernel version: `4.19.241-13212-ge9b0bab46475`

- Chromebrew version: `1.25.3`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: d0cbc01 `Update self.preflight in openjdk8 (#7365) (24 hours ago)`

- OS variant: `Chrome OS`
- OS version: `cyan-release/R103-14816.131.0`
- OS channel: `stable-channel`
***

## Additional information
I don't think its related but any crew command I do will spit out the following then do its command
```shell
Ignoring debug-1.4.0 because its extensions are not built. Try: gem pristine debug --version 1.4.0
```

**Comment by satmandu** [comment]
neovim needs an update... working on that...

The other issue can be addressed by a `gem pristine debug --version 1.4.0`

**Comment by Metal-Toilet** [comment]
I've tried ```gem pristine debug --version 1.4.0``` before and whenever I do it spits out
```shell
Restoring gems to pristine condition...
Building native extensions. This could take a while...
ERROR:  While executing gem ... (Gem::Ext::BuildError)
    ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib64/ruby/gems/3.1.0/gems/debug-1.4.0/ext/debug
/usr/local/bin/ruby -I /usr/local/lib64/ruby/site_ruby/3.1.0 extconf.rb
creating Makefile

current directory: /usr/local/lib64/ruby/gems/3.1.0/gems/debug-1.4.0/ext/debug
make DESTDIR\= sitearchdir\=./.gem.20220905-7792-ve0s4r sitelibdir\=./.gem.20220905-7792-ve0s4r clean
current directory: /usr/local/lib64/ruby/gems/3.1.0/gems/debug-1.4.0/ext/debug
make DESTDIR\= sitearchdir\=./.gem.20220905-7792-ve0s4r sitelibdir\=./.gem.20220905-7792-ve0s4r
make failedNo such file or directory - make

Gem files will remain installed in /usr/local/lib64/ruby/gems/3.1.0/gems/debug-1.4.0 for inspection.
Results logged to /usr/local/lib64/ruby/gems/3.1.0/extensions/x86_64-linux-gnu/3.1.0/debug-1.4.0/gem_make.out
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:77:in `rescue in run'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:74:in `run'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:51:in `block in make'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:43:in `each'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:43:in `make'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:171:in `build_extension'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:205:in `block in build_extensions'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:202:in `each'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/ext/builder.rb:202:in `build_extensions'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/installer.rb:843:in `build_extensions'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/installer.rb:326:in `install'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/commands/pristine_command.rb:190:in `block in execute'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/commands/pristine_command.rb:125:in `each'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/commands/pristine_command.rb:125:in `execute'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/command.rb:323:in `invoke_with_build_args'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:185:in `process_args'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/command_manager.rb:149:in `run'
        /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems/gem_runner.rb:51:in `run'
        /usr/local/bin/gem:13:in `<main>'
``` 
and then continues with the error.

**Comment by satmandu** [comment]
huh.  Try a `crew reinstall ruby` ?

I've got nvim building and working now, but I just need to let it finish building on all architectures.
```
chronos@cheekon-x86_64 ~ $ nvim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by chronos@cheekon-x86_64

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

```

**Comment by Metal-Toilet** [comment]
Thank you! Reinstalling ruby didn't work though. I'm still getting the same error. I don't think its caused any problems (for me) but I thought i'd mention it. Once you've finished building neovim i'll just run ```crew update neovim``` right?

**Comment by satmandu** [comment]
> Thank you! Reinstalling ruby didn't work though. I'm still getting the same error. I don't think its caused any problems (for me) but I thought i'd mention it. Once you've finished building neovim i'll just run ```crew update neovim``` right?

`crew update ; crew upgrade` should take care of it.

**Comment by satmandu** [comment]
(when done)
