### ISSUE TITLE
`crew build` errors with patchelf and upx

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#7448]
This is a general issue with builds after the latest updates.
```
Running patchelf
Running patchelf to patch binaries for library paths
sh: 1: Syntax error: "(" unexpected
Using rdfind to convert duplicate files to hard links.
Now scanning ".", found 155850 files.
Now have 155850 files in total.
Removed 0 files due to nonunique device and inode.
Total size is 866942385 bytes or 827 MiB
Removed 3471 files due to unique sizes from list. 152379 files left.
Now eliminating candidates based on first bytes: removed 16201 files from list. 136178 files left.
Now eliminating candidates based on last bytes: removed 1826 files from list. 134352 files left.
Now eliminating candidates based on sha1 checksum: removed 284 files from list. 134068 files left.
It seems like you have 134068 files that are not unique
Totally, 426 MiB can be reduced.
Now making hard links.
Making 122089 links.
Using upx to shrink binaries.
/usr/local/lib64/ruby/3.1.0/fileutils.rb:1394:in `initialize': No such file or directory @ rb_sysopen - /usr/local/tmp/crew/dest(standard (Errno::ENOENT)
	from /usr/local/lib64/ruby/3.1.0/fileutils.rb:1394:in `open'
	from /usr/local/lib64/ruby/3.1.0/fileutils.rb:1394:in `copy_file'
	from /usr/local/lib64/ruby/3.1.0/fileutils.rb:504:in `copy_file'
	from /usr/local/lib64/ruby/3.1.0/fileutils.rb:423:in `block in cp'
	from /usr/local/lib64/ruby/3.1.0/fileutils.rb:1577:in `block in fu_each_src_dest'
	from /usr/local/lib64/ruby/3.1.0/fileutils.rb:1593:in `fu_each_src_dest0'
	from /usr/local/lib64/ruby/3.1.0/fileutils.rb:1575:in `fu_each_src_dest'
	from /usr/local/lib64/ruby/3.1.0/fileutils.rb:422:in `cp'
	from /usr/local/bin/crew:1156:in `block (2 levels) in shrink_dir'
	from /usr/local/bin/crew:1153:in `each_line'
	from /usr/local/bin/crew:1153:in `block in shrink_dir'
	from /usr/local/bin/crew:1126:in `chdir'
	from /usr/local/bin/crew:1126:in `shrink_dir'
	from /usr/local/bin/crew:1040:in `block in prepare_package'
	from /usr/local/bin/crew:960:in `chdir'
	from /usr/local/bin/crew:960:in `prepare_package'
	from /usr/local/bin/crew:1471:in `build_package'
	from /usr/local/bin/crew:1436:in `resolve_dependencies_and_build'
	from /usr/local/bin/crew:1692:in `block in build_command'
	from /usr/local/bin/crew:1688:in `each'
	from /usr/local/bin/crew:1688:in `build_command'
	from /usr/local/bin/crew:1873:in `<main>'
```

**Comment by satmandu** [comment]
Please attach the package files you are trying to build?

**Comment by satmandu** [comment]
Successful build log attached.

```
require 'package'

class Heroku < Package
  description 'The Heroku Command Line Interface (CLI), formerly known as the Heroku Toolbelt, is a tool for creating and managing Heroku apps from the command line / shell of various operating systems.'
  homepage 'https://devcenter.heroku.com/articles/heroku-cli'
  version '7.63.4'
  license 'Heroku-TOS'
  compatibility 'all'
  source_url 'https://github.com/heroku/cli/archive/v7.63.4.tar.gz'
  source_sha256 '3cb7577cc4c78dcace8a6d6521914441a569bab364e555d8a2fdf497661f61c4'

  binary_url({
    x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/heroku/7.63.4_x86_64/heroku-7.63.4-chromeos-x86_64.tar.zst'
  })
  binary_sha256({
    x86_64: '4bad7c1d7117c1973b9574fd665a36ef305f151e7c4aeeba2ec7cfb55c815258'
  })

  depends_on 'yarn' => :build # Use node version 16.

  no_patchelf

  def self.build
    system 'npx -y nx init'
    system 'npx -y lerna@latest init'
    system 'npx -y lerna bootstrap'
    system 'npx lerna run build'
  end

  def self.check
    system 'npx lerna run test || true'
  end

  def self.install
    FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/bin"
    FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/share/heroku"
    FileUtils.cp_r '.', "#{CREW_DEST_PREFIX}/share/heroku"
    FileUtils.ln_s "#{CREW_PREFIX}/share/heroku/bin/run", "#{CREW_DEST_PREFIX}/bin/heroku"
  end
end
```
[heroku-7.63.4-x86_64.log](https://github.com/chromebrew/chromebrew/files/9693866/heroku-7.63.4-x86_64.log)

Problem may be on your system?

**Comment by uberhacker** [comment]
I ran `crew upgrade` to get the latest code so the master branch is in sync.

**Comment by satmandu** [comment]
This is the code I use to start my container:
```
#!/bin/bash
docker pull satmandu/crewbuild:nocturne-x86_64.m90
docker pull tonistiigi/binfmt
docker run --privileged --rm tonistiigi/binfmt --install all
docker run --platform linux/amd64 --rm -v $(pwd)/pkg_cache:/usr/local/tmp/packages -v $(pwd):/output -h $(hostname)-x86_64 -it satmandu/crewbuild:nocturne-x86_64.m90 /usr/local/bin/setarch x86_64 sudo -i -u chronos /usr/local/bin/bash -i
```

**Comment by uberhacker** [comment]
I didn't get this in my build:
```
Stripping binaries...
./usr/local/share/heroku/.github/build/entrypoint.sh: line 1: warning: command substitution: ignored null byte in input
./usr/local/share/heroku/.github/build/entrypoint.sh: line 1: warning: command substitution: ignored null byte in input
./usr/local/share/heroku/.github/build/entrypoint.sh: line 1: warning: command substitution: ignored null byte in input
./usr/local/share/heroku/.github/build/entrypoint.sh: line 1: warning: command substitution: ignored null byte in input
./usr/local/share/heroku/.github/build/entrypoint.sh: line 1: warning: command substitution: ignored null byte in input
```
Something wrong in your container?

**Comment by satmandu** [comment]
Stripping a shell script doesn't do anything?

```
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ crew whatprovides entrypoint.sh
heroku: /usr/local/share/heroku/.github/build/entrypoint.sh

Total found: 1
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ cat /usr/local/share/heroku/.github/build/entrypoint.sh
#!/bin/sh -l

sh -c "echo $*"
chronos@cheekon-
```

**Comment by satmandu** [comment]
Does building in my container work for you?

**Comment by uberhacker** [comment]
So you were right.  I reinstalled ruby and the error went away.  What about patchelf?  Do you get the same error after removing `no_patchelf`?

**Comment by uberhacker** [comment]
Reinstalling ruby fixed this for me.
