### ISSUE TITLE
[buildessential] Upgrade doesn't install rubocop

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#7491]
```
Package lists, crew, and library updated.
Checking for package updates...
buildessential could be updated from 1.19 to 1.20

Run `crew upgrade` to update all packages or `crew upgrade <package1> [<package2> ...]` to update specific packages.
$ crew upgrade
Updating packages...
buildessential: A collection of tools essential to compile and build software.
Performing pre-flight checks...
Removing since upgrade or reinstall...
Buildessential removed!
Buildessential installed!
Packages have been updated.
$ rubocop
/usr/local/lib64/ruby/site_ruby/3.1.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem rubocop (>= 0.a) with executable rubocop (Gem::GemNotFoundException)
	from /usr/local/lib64/ruby/site_ruby/3.1.0/rubygems.rb:284:in `activate_bin_path'
	from /usr/local/bin/rubocop:25:in `<main>'
```

**Comment by uberhacker** [comment]
Apparently so.
