### ISSUE TITLE
[ruby_rubocop] rubocop executable not working

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#7492]
Broken on both arm and i686 containers.
```
$ rubocop -h
/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1453:in `rescue in block in activate_dependencies': Could not find 'parallel' (~> 1.10) among 93 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/usr/local/.config/.local/share/gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0' at: /usr/local/lib/ruby/gems/3.1.0/specifications/rubocop-1.26.1.gemspec, execute `gem env` for more information
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1450:in `block in activate_dependencies'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1439:in `each'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1439:in `activate_dependencies'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1421:in `activate'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:286:in `block in activate_bin_path'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:285:in `synchronize'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:285:in `activate_bin_path'
	from /usr/local/bin/rubocop:25:in `<main>'
/usr/local/lib/ruby/site_ruby/3.1.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'parallel' (~> 1.10) among 93 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/usr/local/.config/.local/share/gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0' , execute `gem env` for more information
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1451:in `block in activate_dependencies'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1439:in `each'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1439:in `activate_dependencies'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems/specification.rb:1421:in `activate'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:286:in `block in activate_bin_path'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:285:in `synchronize'
	from /usr/local/lib/ruby/site_ruby/3.1.0/rubygems.rb:285:in `activate_bin_path'
	from /usr/local/bin/rubocop:25:in `<main>'
```

**Comment by satmandu** [comment]
Why aren't those getting installed automatically?

**Comment by uberhacker** [comment]
No idea.  Maybe something is missing in the binaries?

**Comment by uberhacker** [comment]
Yes, closing...
