### ISSUE TITLE
crew install issue

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#7601]
```
Setup and synchronize local package repo...

     -=O=-#     #       #         #                                                                                                                 
sh: 1: python3: not found
sh: 1: python3: not found
Installing core Chromebrew packages...
```
Looks like something is trying to execute python before it was installed.

**Comment by uberhacker** [comment]
It appears to be happening at `crew update compatibility` line in install.sh.

**Comment by satmandu** [comment]
```
crew install strace
strace crew update compatible &> /tmp/out
```

```
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ grep -v "\.rb" /tmp/out  | grep -5 python
fstat(5, {st_mode=S_IFREG|0644, st_size=2703, ...}) = 0
lseek(5, 0, SEEK_CUR)                   = 0
read(5, "require 'package'\n\nclass Dropbox"..., 2703) = 2703
read(5, "", 8192)                       = 0
close(5)                                = 0
stat("/usr/local/bin/python", {st_mode=S_IFREG|0755, st_size=24984, ...}) = 0
ioctl(5, TCGETS, 0x7ffc2d1ec5d0)        = -1 ENOTTY (Inappropriate ioctl for device)
fstat(5, {st_mode=S_IFREG|0644, st_size=2079, ...}) = 0
lseek(5, 0, SEEK_CUR)                   = 0
read(5, "require 'package'\n\nclass Dropbox"..., 2079) = 2079
read(5, "", 8192)                       = 0
--
fstat(5, {st_mode=S_IFREG|0644, st_size=1609, ...}) = 0
lseek(5, 0, SEEK_CUR)                   = 0
read(5, "require 'package'\n\nclass Percona"..., 1609) = 1609
read(5, "", 8192)                       = 0
close(5)                                = 0
stat("/usr/local/bin/python", {st_mode=S_IFREG|0755, st_size=24984, ...}) = 0
ioctl(5, TCGETS, 0x7ffc2d1ec5d0)        = -1 ENOTTY (Inappropriate ioctl for device)
fstat(5, {st_mode=S_IFREG|0644, st_size=5346, ...}) = 0
lseek(5, 0, SEEK_CUR)                   = 0
read(5, "require 'package'\n\nclass Percona"..., 5346) = 5346
read(5, "", 8192)                       = 0
--
fstat(5, {st_mode=S_IFREG|0644, st_size=2042, ...}) = 0
lseek(5, 0, SEEK_CUR)                   = 0
read(5, "require 'package'\n\nclass Sqlmap "..., 2042) = 2042
read(5, "", 8192)                       = 0
close(5)                                = 0
stat("/usr/local/bin/python", {st_mode=S_IFREG|0755, st_size=24984, ...}) = 0
ioctl(5, TCGETS, 0x7ffc2d1ec5d0)        = -1 ENOTTY (Inappropriate ioctl for device)
fstat(5, {st_mode=S_IFREG|0644, st_size=2134, ...}) = 0
lseek(5, 0, SEEK_CUR)                   = 0
read(5, "require 'package'\n\nclass Squashf"..., 2134) = 2134
read(5, "", 8192)                       = 0
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ 
```
Looking at those files I see this:
```
  depends_on 'python2' unless File.exist? "#{CREW_PREFIX}/bin/python"
```
or this:
```
  depends_on 'python27' unless File.exist? "#{CREW_PREFIX}/bin/python"
```

Is it possible this is what is causing that error?

**Comment by supechicken** [comment]
Sometimes the verbose option is a good thing :)
```
 $ rm -rf /usr/local/bin/python3
chronos@localhost / $ crew update compatible -v 2>&1 | grep -B1 python3
Adding py3_cmarkgfm 2022.3.4 to compatible packages.
sh: 1: python3: not found
sh: 1: python3: not found
```

**Comment by supechicken** [comment]
Got some hints after replacing the backtick function with the trace code below:
```ruby
module Backtick
  def `(args)
    puts "system(): #{caller[0]}".lightcyan
    p args
    return IO.popen(args, 'r').read
  end
end

include Backtick
```
```
system(): /usr/local/lib/crew/packages/py3_codespell.rb:28:in `<class:Py3_codespell>'
"python3 -V | cut -d' ' -f2 | cut -d'.' -f1"
sh: 1: python3: not found
system(): /usr/local/lib/crew/packages/py3_codespell.rb:29:in `<class:Py3_codespell>'
"python3 -V | cut -d' ' -f2 | cut -d'.' -f2"
sh: 1: python3: not found
```
