### ISSUE TITLE
🐞 Progress bar Error message

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#8012]
When building a package from git on armv7l...
```
/usr/local/lib/crew/lib/downloader.rb:141:in `ensure in block (2 levels) in http_downloader': undefined method `progress_bar_showing=' for nil:NilClass (NoMethodError)

      progress_bar.progress_bar_showing = false
                  ^^^^^^^^^^^^^^^^^^^^^^^
        from /usr/local/lib/crew/lib/downloader.rb:142:in `block (2 levels) in http_downloader'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1873:in `block in transport_request'
        from /usr/local/lib/ruby/3.2.0/net/http/response.rb:301:in `reading_body'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1872:in `transport_request'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1826:in `request'
        from /usr/local/lib/crew/lib/downloader.rb:88:in `block in http_downloader'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:1238:in `start'
        from /usr/local/lib/ruby/3.2.0/net/http.rb:687:in `start'
        from /usr/local/lib/crew/lib/downloader.rb:81:in `http_downloader'
        from /usr/local/lib/crew/lib/downloader.rb:40:in `downloader'
        from /usr/local/lib/crew/packages/ffmpeg.rb:111:in `patch'
        from /usr/local/bin/crew:956:in `block in build_and_preconfigure'
        from /usr/local/bin/crew:946:in `chdir'
        from /usr/local/bin/crew:946:in `build_and_preconfigure'
        from /usr/local/bin/crew:1535:in `build_package'
        from /usr/local/bin/crew:1512:in `resolve_dependencies_and_build'
        from /usr/local/bin/crew:1730:in `block in build_command'
        from /usr/local/bin/crew:1726:in `each'
        from /usr/local/bin/crew:1726:in `build_command'
        from /usr/local/bin/crew:1919:in `<main>'
Building from source, this may take a while...
######################################################################## 100.0%
```

This is related the this morning's PR @supechicken, no?

**Comment by satmandu** [comment]
As per @uberhacker. ` temp fix for the downloader issue: comment lines 141 and 142 in lib/downloader.rb`...

**Comment by supechicken** [comment]
Oh, I forgot to test with HTTP redirection...
