### ISSUE TITLE
🐞 meson_options not being seen

### ISSUE THREAD

**Issue by satmandu** [chromebrew/chromebrew#8540]
```
From https://github.com/chromebrew/chromebrew
 * branch              master     -> FETCH_HEAD
Updating files: 100% (3962/3962), done.
HEAD is now at 42a838af [g]emacs => 29.1 (#8537)
Package lists, crew, and library updated.
Error with vte.rb: undefined method `meson_options' for Package::Vte:Class
Checking for package updates...
Your software is up to date.
chronos@rpi4b-armv7l /usr/local/lib/crew/packages $ 
```

And this is the relevant `vte.rb`:
```ruby
require 'buildsystems/meson'

class Vte < Meson
  description 'Virtual Terminal Emulator widget for use with GTK'
  homepage 'https://wiki.gnome.org/Apps/Terminal/VTE'
  version '0.72.2'
  license 'LGPL-2+ and GPL-3+'
  compatibility 'x86_64 aarch64 armv7l'
  source_url 'https://gitlab.gnome.org/GNOME/vte.git'
  git_hashtag version

  binary_url({
    aarch64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/vte/0.72.2_armv7l/vte-0.72.2-chromeos-armv7l.tar.zst',
     armv7l: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/vte/0.72.2_armv7l/vte-0.72.2-chromeos-armv7l.tar.zst',
     x86_64: 'https://gitlab.com/api/v4/projects/26210301/packages/generic/vte/0.72.2_x86_64/vte-0.72.2-chromeos-x86_64.tar.zst'
  })
  binary_sha256({
    aarch64: 'e90bfce1c8449ef74c9acf5a3eeb4f365ffa39c008fe398ff3c6b7042dfc3520',
     armv7l: 'e90bfce1c8449ef74c9acf5a3eeb4f365ffa39c008fe398ff3c6b7042dfc3520',
     x86_64: '1c86607d53f6a6f1738770c14b06df6e5cc95f43ce9e6d54a00a1f4ec97f3017'
  })

  depends_on 'at_spi2_core' # R
  depends_on 'cairo' # R
  depends_on 'fribidi' # R
  depends_on 'gcc_lib' # R
  depends_on 'gdk_pixbuf' # R
  depends_on 'glibc' # R
  depends_on 'glib' # R
  depends_on 'gnutls' # R
  depends_on 'gobject_introspection' => :build
  depends_on 'graphene' # R
  depends_on 'gtk3' # R
  depends_on 'gtk4' # R
  depends_on 'harfbuzz' # R
  depends_on 'icu4c' # R
  depends_on 'pango' # R
  depends_on 'pcre2' # R
  depends_on 'vulkan_headers' => :build
  depends_on 'vulkan_icd_loader' # R
  depends_on 'zlibpkg' # R

  gnome
  no_lto

  meson_options '-D_systemd=false \
      -Dfribidi=true \
      -Dgtk3=true \
      -Dgtk4=true \
      -Dgir=false \
      -Dvapi=false'
end
```

Any thoughts @supechicken ?

**Comment by satmandu** [comment]
I assume it is something simple I have missed?

**Comment by satmandu** [comment]
```ruby
$ grep -r "cmake_options\|meson_options" .
./lib/buildsystems/meson.rb:  def self.meson_options(options = '')
./lib/buildsystems/meson.rb:    return (@meson_options = options if options)
./lib/buildsystems/meson.rb:    puts "Additional meson_options being used: #{@meson_options.nil? || @meson_options.empty? ? '<no meson_options>' : @meson_options}".orange
./lib/buildsystems/meson.rb:    @crew_meson_options = @no_lto ? CREW_MESON_FNO_LTO_OPTIONS : CREW_MESON_OPTIONS
./lib/buildsystems/meson.rb:    system "#{@mold_linker_prefix_cmd} meson setup #{@crew_meson_options} #{@meson_options} builddir"
./lib/buildsystems/cmake.rb:  def self.cmake_options(options = '')
./lib/buildsystems/cmake.rb:    return (@cmake_options = options if options)
./lib/buildsystems/cmake.rb:    puts "Additional cmake_options being used: #{@cmake_options.nil? || @cmake_options.empty? ? '<no cmake_options>' : @cmake_options}".orange
./lib/buildsystems/cmake.rb:    @crew_cmake_options = @no_lto ? CREW_CMAKE_FNO_LTO_OPTIONS : CREW_CMAKE_OPTIONS
./lib/buildsystems/cmake.rb:    system "#{@mold_linker_prefix_cmd} cmake -B builddir -G Ninja #{@crew_cmake_options} #{@cmake_options}"
./packages/libgit2.rb:  cmake_options '-DUSE_SSH=ON -DUSE_BUNDLED_ZLIB=OFF'
./packages/inkscape.rb:  cmake_options '-DWITH_IMAGE_MAGICK=OFF \
./packages/cppdap.rb:  cmake_options '-DBUILD_SHARED_LIBS=ON'
./packages/c_ares.rb:  cmake_options '-DCARES_STATIC=ON \
./packages/tbb.rb:    @tbb_cmake_options = if ARCH == 'i686'
./packages/tbb.rb:      system "cmake #{@tbb_cmake_options} \
./packages/vte.rb:  meson_options '-D_systemd=false \
```

**Comment by supechicken** [comment]
Does the error only appear during `crew update`? (I didn't get any error with `crew install -s` and `meson_options`)

**Comment by satmandu** [comment]
> Does the error only appear during `crew update`? (I didn't get any error with `crew install -s` and `meson_options`)

This happens only when building and a dependency is using `meson_options`.

With `cairo.rb` using `meson_options`, it happens when building `libdrm`, and then also when building `libtiff`.

I can comment out the `meson_options` line in the dependency, and the build goes just fine.

**Comment by satmandu** [comment]
@supechicken This is also causing problems on install of packages now:

```
$ crew install torbrowser
torbrowser: 'The Onion Router' browser
https://www.torproject.org/
Version: 12.5.5
License: BSD, custom, MPL-2.0 and MIT
Performing pre-flight checks...
/usr/local/lib/crew/packages//cairo.rb:40:in `<class:Cairo>': undefined method `meson_options' for Package::Torbrowser::Cairo:Class (NoMethodError)
Did you mean?  no_env_options
	from /usr/local/lib/crew/packages//cairo.rb:3:in `load_package'
	from /usr/local/lib/crew/lib/package.rb:38:in `class_eval'
	from /usr/local/lib/crew/lib/package.rb:38:in `load_package'
	from /usr/local/lib/crew/lib/package.rb:80:in `get_deps_list'
	from /usr/local/lib/crew/lib/package.rb:108:in `block in get_deps_list'
	from /usr/local/lib/crew/lib/package.rb:94:in `map'
	from /usr/local/lib/crew/lib/package.rb:94:in `get_deps_list'
	from /usr/local/lib/crew/lib/package.rb:108:in `block in get_deps_list'
	from /usr/local/lib/crew/lib/package.rb:94:in `map'
	from /usr/local/lib/crew/lib/package.rb:94:in `get_deps_list'
	from /usr/local/bin/crew:1454:in `resolve_dependencies'
	from /usr/local/bin/crew:1431:in `resolve_dependencies_and_install'
	from /usr/local/bin/crew:1891:in `block in install_command'
	from /usr/local/bin/crew:1886:in `each'
	from /usr/local/bin/crew:1886:in `install_command'
	from /usr/local/bin/crew:2018:in `<main>'
```
Also:
```
$ crew install torbrowser
torbrowser: 'The Onion Router' browser
https://www.torproject.org/
Version: 12.5.5
License: BSD, custom, MPL-2.0 and MIT
Performing pre-flight checks...
/usr/local/lib/crew/packages//libdrm.rb:30:in `<class:Libdrm>': undefined method `meson_options' for Package::Torbrowser::Libdrm:Class (NoMethodError)
```

**Comment by satmandu** [comment]
Ok, I figured this out. `buildsystems/meson.rb` conflicts with `packages/meson.rb`.

We need to rename one of them.

I suggest we rename  `packages/meson.rb` to  `packages/mesonbuild.rb`.

Any objections? @supechicken @uberhacker
