### ISSUE TITLE
🐞 Error running java from OpenJDK17

### ISSUE THREAD

**Issue by grandpa1946** [chromebrew/chromebrew#8748]
**Describe the bug**
getting an error when running any java command after installing openjdk17 with all latest deps
**To Reproduce**

1. I executed this command:

      ```shell
      java
      ```

      Output:

      ```
      Exception in thread "main" java.lang.InternalError: Error loading java.security file
        at java.base/java.security.Security.initialize(Security.java:106)
        at java.base/java.security.Security$1.run(Security.java:84)
        at java.base/java.security.Security$1.run(Security.java:82)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.base/java.security.Security.<clinit>(Security.java:82)
        at java.base/sun.security.util.SecurityProperties.getOverridableProperty(SecurityProperties.java:57)
        at java.base/sun.security.util.SecurityProperties.privilegedGetOverridable(SecurityProperties.java:48)
        at java.base/sun.security.util.SecurityProperties.includedInExceptions(SecurityProperties.java:72)
        at java.base/sun.security.util.SecurityProperties.<clinit>(SecurityProperties.java:36)
        at java.base/sun.security.util.FilePermCompat.<clinit>(FilePermCompat.java:45)
        at java.base/java.security.AccessControlContext.<init>(AccessControlContext.java:269)
        at java.base/java.security.AccessController.createWrapper(AccessController.java:647)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:460)
        at java.base/java.util.ResourceBundle$ResourceBundleProviderHelper.loadResourceBundle(ResourceBundle.java:3614)
        at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1837)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1768)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1656)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1575)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:858)
        at java.base/sun.launcher.LauncherHelper$ResourceBundleHolder.<clinit>(LauncherHelper.java:125)
        at java.base/sun.launcher.LauncherHelper.getLocalizedMessage(LauncherHelper.java:483)
        at java.base/sun.launcher.LauncherHelper.initHelpMessage(LauncherHelper.java:495)
      ```

**Expected behavior**
java help popping up
**Screenshots**

**Environment: Paste the output of `crew sysinfo -v` between the two `***` below**

***
<details><summary>Expand</summary>

- Architecture: `x86_64` (`x86_64`)
- Processor vendor: `AuthenticAMD`
- User space: `64-bit`
- Chromebrew Kernel version: `5.4`
- Chromebrew Running in Container: `false`

- Chromebrew version: `1.35.6`
- Chromebrew prefix: `/usr/local`
- Chromebrew libdir: `/usr/local/lib64`

- Last update in local repository: 6bdc6e02 `Openssh 9.4p1 => 9.5p1 (#8740) (3 hours ago)`

- OS variant: `Chrome OS`
- OS version: `zork-release/R116-15509.81.0`
- OS channel: `stable-channel`

</details>
***

**Additional context**

What I think needs to be done:

      - [ ] step one
      - [ ] step two

**Comment by satmandu** [comment]
@uberhacker I'm still seeing this issue.
```
From https://github.com/chromebrew/chromebrew
 * branch              master     -> FETCH_HEAD
   49377ca1..fbfbc61c  master     -> origin/master
HEAD is now at fbfbc61c rebuild libcue, update packages depending upon libcue (#8766)
Package lists, crew, and library updated.
Checking for package updates...
sqlite could be updated (rebuild)
sqlite could be updated from 3.43.1 to 3.43.2
                                                                                                                                                                                                              Run `crew upgrade` to update all packages or `crew upgrade <package1> [<package2> ...]` to update specific packages.
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ crew upgrade
Updating packages...
sqlite: SQLite is a self-contained, high-reliability, embedded, full-featured, public-domain, SQL database engine.
Performing pre-flight checks...
Precompiled binary available, downloading...
Archive found in cache
Unpacking archive using 'tar', this may take a while...
Removing since upgrade or reinstall...
Checking for conflicts of sqlite with files from installed packages...
Sqlite removed!
Performing pre-install...
Performing install...
Using rdfind to convert duplicate files to hard links.
Now scanning ".", found 8 files.
Now have 8 files in total.
Removed 0 files due to nonunique device and inode.
Total size is 11412044 bytes or 11 MiB
Removed 8 files due to unique sizes from list. 0 files left.
Now eliminating candidates based on first bytes: removed 0 files from list. 0 files left.
Now eliminating candidates based on last bytes: removed 0 files from list. 0 files left.
Now eliminating candidates based on sha1 checksum: removed 0 files from list. 0 files left.
It seems like you have 0 files that are not unique
Totally, 0 B can be reduced.
Now making hard links.
Making 0 links.
Sqlite installed!
Packages have been updated.
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ crew install openjdk17
openjdk17: The JDK is a development environment for building applications, applets, and components using the Java programming language.
https://openjdk.org/
Version: 17.0.8
License: GPL-2
Performing pre-flight checks...
No precompiled binary available for your platform, downloading source...
Archive found in cache
Unpacking archive using 'tar', this may take a while...
Preconfiguring package...
jar.1                : 35.05%   (  11.4 KiB =>   3.99 KiB, jar.1.zst)
jarsigner.1          : 28.34%   (  54.6 KiB =>   15.5 KiB, jarsigner.1.zst)
java.1               : 26.63%   (   184 KiB =>   49.0 KiB, java.1.zst)
javac.1              : 27.79%   (  83.1 KiB =>   23.1 KiB, javac.1.zst)
javadoc.1            : 30.78%   (  45.5 KiB =>   14.0 KiB, javadoc.1.zst)
javap.1              : 36.03%   (  7.63 KiB =>   2.75 KiB, javap.1.zst)
jcmd.1               : 23.38%   (  34.5 KiB =>   8.06 KiB, jcmd.1.zst)
jconsole.1           : 45.48%   (  3.58 KiB =>   1.63 KiB, jconsole.1.zst)
jdb.1                : 38.61%   (  8.69 KiB =>   3.36 KiB, jdb.1.zst)
jdeprscan.1          : 38.89%   (  7.95 KiB =>   3.09 KiB, jdeprscan.1.zst)
jdeps.1              : 31.23%   (  12.0 KiB =>   3.74 KiB, jdeps.1.zst)
jfr.1                : 34.78%   (  8.82 KiB =>   3.07 KiB, jfr.1.zst)
jhsdb.1              : 32.23%   (  7.17 KiB =>   2.31 KiB, jhsdb.1.zst)
jinfo.1              : 46.13%   (  3.42 KiB =>   1.58 KiB, jinfo.1.zst)
jlink.1              : 33.44%   (  11.7 KiB =>   3.90 KiB, jlink.1.zst)
jmap.1               : 46.59%   (  3.41 KiB =>   1.59 KiB, jmap.1.zst)
jmod.1               : 33.93%   (  11.8 KiB =>   4.01 KiB, jmod.1.zst)
jpackage.1           : 31.82%   (  14.5 KiB =>   4.60 KiB, jpackage.1.zst)
jps.1                : 36.84%   (  8.26 KiB =>   3.04 KiB, jps.1.zst)
jrunscript.1         : 42.53%   (  5.16 KiB =>   2.19 KiB, jrunscript.1.zst)
jshell.1             : 23.86%   (  42.7 KiB =>   10.2 KiB, jshell.1.zst)
jstack.1             : 50.62%   (  2.98 KiB =>   1.51 KiB, jstack.1.zst)
jstat.1              : 26.99%   (  23.5 KiB =>   6.35 KiB, jstat.1.zst)
jstatd.1             : 37.79%   (  7.69 KiB =>   2.91 KiB, jstatd.1.zst)
keytool.1            : 25.12%   (   109 KiB =>   27.4 KiB, keytool.1.zst)
rmiregistry.1        : 47.05%   (  3.18 KiB =>   1.50 KiB, rmiregistry.1.zst)
serialver.1          : 48.27%   (  2.84 KiB =>   1.37 KiB, serialver.1.zst)
Checking for FHS3 compliance...
Performing pre-install...
Performing install...
Using rdfind to convert duplicate files to hard links.
Now scanning ".", found 208 files.
Now have 208 files in total.
Removed 0 files due to nonunique device and inode.
Total size is 332105068 bytes or 317 MiB
Removed 176 files due to unique sizes from list. 32 files left.
Now eliminating candidates based on first bytes: removed 5 files from list. 27 files left.
Now eliminating candidates based on last bytes: removed 0 files from list. 27 files left.
Now eliminating candidates based on sha1 checksum: removed 23 files from list. 4 files left.
It seems like you have 4 files that are not unique
Totally, 13 KiB can be reduced.
Now making hard links.
Making 2 links.
Openjdk17 installed!
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ java
Exception in thread "main" java.lang.InternalError: Error loading java.security file
        at java.base/java.security.Security.initialize(Security.java:106)                                                                                                                                             at java.base/java.security.Security$1.run(Security.java:84)
        at java.base/java.security.Security$1.run(Security.java:82)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.base/java.security.Security.<clinit>(Security.java:82)
        at java.base/sun.security.util.SecurityProperties.getOverridableProperty(SecurityProperties.java:57)
        at java.base/sun.security.util.SecurityProperties.privilegedGetOverridable(SecurityProperties.java:48)                                                                                                        at java.base/sun.security.util.SecurityProperties.includedInExceptions(SecurityProperties.java:72)
        at java.base/sun.security.util.SecurityProperties.<clinit>(SecurityProperties.java:36)
        at java.base/sun.security.util.FilePermCompat.<clinit>(FilePermCompat.java:45)                                                                                                                                at java.base/java.security.AccessControlContext.<init>(AccessControlContext.java:269)
        at java.base/java.security.AccessController.createWrapper(AccessController.java:647)                                                                                                                          at java.base/java.security.AccessController.doPrivileged(AccessController.java:460)
        at java.base/java.util.ResourceBundle$ResourceBundleProviderHelper.loadResourceBundle(ResourceBundle.java:3614)
        at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1837)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1768)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1656)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1575)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:858)
        at java.base/sun.launcher.LauncherHelper$ResourceBundleHolder.<clinit>(LauncherHelper.java:125)                                                                                                               at java.base/sun.launcher.LauncherHelper.getLocalizedMessage(LauncherHelper.java:483)
        at java.base/sun.launcher.LauncherHelper.initHelpMessage(LauncherHelper.java:495)
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ bash
This is the .bashrc
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ java
Exception in thread "main" java.lang.InternalError: Error loading java.security file
        at java.base/java.security.Security.initialize(Security.java:106)
        at java.base/java.security.Security$1.run(Security.java:84)
        at java.base/java.security.Security$1.run(Security.java:82)                                                                                                                                                   at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.base/java.security.Security.<clinit>(Security.java:82)
        at java.base/sun.security.util.SecurityProperties.getOverridableProperty(SecurityProperties.java:57)
        at java.base/sun.security.util.SecurityProperties.privilegedGetOverridable(SecurityProperties.java:48)                                                                                                        at java.base/sun.security.util.SecurityProperties.includedInExceptions(SecurityProperties.java:72)
        at java.base/sun.security.util.SecurityProperties.<clinit>(SecurityProperties.java:36)                                                                                                                        at java.base/sun.security.util.FilePermCompat.<clinit>(FilePermCompat.java:45)
        at java.base/java.security.AccessControlContext.<init>(AccessControlContext.java:269)                                                                                                                         at java.base/java.security.AccessController.createWrapper(AccessController.java:647)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:460)                                                                                                                           at java.base/java.util.ResourceBundle$ResourceBundleProviderHelper.loadResourceBundle(ResourceBundle.java:3614)                                                                                               at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1837)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1768)                                                                                                                                    at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
        at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)                                                                                                                                    at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1656)
        at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1575)                                                                                                                                 at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
        at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:858)
        at java.base/sun.launcher.LauncherHelper$ResourceBundleHolder.<clinit>(LauncherHelper.java:125)
        at java.base/sun.launcher.LauncherHelper.getLocalizedMessage(LauncherHelper.java:483)
        at java.base/sun.launcher.LauncherHelper.initHelpMessage(LauncherHelper.java:495)

**Comment by satmandu** [comment]
This is maybe the issue? https://www.reddit.com/r/debian/comments/14bypwg/problems_after_directly_upgrading_to_debian_12/jokj0aq/

**Comment by satmandu** [comment]
Also another description of a related issue?  https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/2019908

**Comment by satmandu** [comment]
Ok this appears to fix things:
```ruby
require 'package'

class Openjdk17 < Package
  description 'The JDK is a development environment for building applications, applets, and components using the Java programming language.'
  homepage 'https://openjdk.org/'
  version '17.0.8-1'
  license 'GPL-2'
  compatibility 'all'
  source_url({
    aarch64: 'https://cdn.azul.com/zulu-embedded/bin/zulu17.44.15-ca-jdk17.0.8-linux_aarch32hf.tar.gz',
     armv7l: 'https://cdn.azul.com/zulu-embedded/bin/zulu17.44.15-ca-jdk17.0.8-linux_aarch32hf.tar.gz',
       i686: 'https://cdn.azul.com/zulu/bin/zulu17.44.15-ca-jdk17.0.8-linux_i686.tar.gz',
     x86_64: 'https://cdn.azul.com/zulu/bin/zulu17.44.15-ca-jdk17.0.8-linux_x64.tar.gz'
  })
  source_sha256({
    aarch64: '4feb1f6cba26c66160e03284b876071ee9d27954df2e2be51def935afc30d8d9',
     armv7l: '4feb1f6cba26c66160e03284b876071ee9d27954df2e2be51def935afc30d8d9',
       i686: 'bc84c25f53f6961c5649f1fd363e944d48113ead07020ba90a2b3d53cea1b5eb',
     x86_64: '423d1f40e0cbe873f357cebb95b19a59503948ee3c91639ecbc8e64df6a6f5fc'
  })

  no_compile_needed
  no_shrink

  def self.preflight
    jdkver = `java -version 2>&1`[/version "(.*?)"/, 1].to_s
    unless jdkver.empty? || jdkver.include?('No such file or directory') || jdkver.include?('not found')
      jdkname = `java -version 2>&1`[/(.*?)\s/, 1].to_s
      jdkname = 'jdk' if jdkname == 'java'
      majver = jdkver[/(\d+)\./, 1].to_s
      majver = '8' if majver == '1'
      unless jdkname == 'openjdk' && majver == '17'
        puts "Package #{jdkname}#{majver} already installed.".lightgreen
        abort "Enter `crew remove #{jdkname}#{majver} && crew install openjdk17` to install this version."
      end
    end
  end

  def self.install
    FileUtils.mkdir_p CREW_DEST_MAN_PREFIX
    FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/share/openjdk17"
    FileUtils.mv Dir['*'], "#{CREW_DEST_PREFIX}/share/openjdk17/"
    FileUtils.mkdir_p "#{CREW_DEST_PREFIX}/bin"
    Dir["#{CREW_DEST_PREFIX}/share/openjdk17/bin/*"].each do |binfile|
      @basename = File.basename(binfile)
      FileUtils.ln_s "#{CREW_PREFIX}/share/openjdk17/bin/#{@basename}", "#{CREW_DEST_PREFIX}/bin/#{@basename}"
    end
    FileUtils.mv Dir["#{CREW_DEST_PREFIX}/share/openjdk17/man/*"], CREW_DEST_MAN_PREFIX
  end
end
```

**Comment by grandpa1946** [comment]
sorry i wasn't really reading my notifs, but thanks for fixing it!
