### ISSUE TITLE
🐞 Bug Download progress bar error

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#9522]
```
25h#<Thread:0x00007f90b542f8b8 /usr/local/lib/crew/lib/progress_bar.rb:82 run> terminated with exception (report_on_exception is true):
/usr/local/lib/crew/lib/progress_bar.rb:97:in `*': negative argument (ArgumentError)

        print (@bar_char * completed_length).send(*@bar_front_color),
                           ^^^^^^^^^^^^^^^^
	from /usr/local/lib/crew/lib/progress_bar.rb:97:in `block in show'
/usr/local/lib/crew/lib/progress_bar.rb:97:in `*': negative argument (ArgumentError)

        print (@bar_char * completed_length).send(*@bar_front_color),
                           ^^^^^^^^^^^^^^^^
	from /usr/local/lib/crew/lib/progress_bar.rb:97:in `block in show'
#=#=#                                                                          
##O#-#
```
Any idea what might be causing this @supechicken?

**Comment by supechicken** [comment]
Umm, which package are you trying to download? Probably related to an unexpected `Content-Length` value from download server.
