### ISSUE TITLE
🐞 Bug Reinstalling packages from source that require build dependencies generates an error

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/chromebrew#9820]
```
$ crew reinstall sommelier -s
sommelier: Sommelier works by redirecting X11 programs to the built-in ChromeOS Exo Wayland server.
Performing pre-flight checks...
The following packages also need to be installed: 
llvm18_dev
Do you agree? [Y/n] 
Proceeding...
llvm18_dev: LLVM: Everything except libLLVM & llvm-strip
Precompiled binary available, downloading...
Performing pre-install...
Performing install...
/usr/local/lib64/ruby/3.3.0/fileutils.rb:1169:in `rename': No such file or directory @ rb_file_s_rename - (dlist, /usr/local/etc/crew/meta/llvm18_dev.directorylist) (Errno::ENOENT)
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:1169:in `block in mv'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:2469:in `block in fu_each_src_dest'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:2485:in `fu_each_src_dest0'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:2467:in `fu_each_src_dest'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:1160:in `mv'
        from /usr/local/bin/crew:1079:in `block in install_package'
        from /usr/local/bin/crew:1075:in `chdir'
        from /usr/local/bin/crew:1075:in `install_package'
        from /usr/local/bin/crew:1304:in `install'
        from /usr/local/bin/crew:1240:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1237:in `each'
        from /usr/local/bin/crew:1237:in `resolve_dependencies'
        from /usr/local/bin/crew:1120:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1829:in `block in reinstall_command'
        from /usr/local/bin/crew:1819:in `each'
        from /usr/local/bin/crew:1819:in `reinstall_command'
        from /usr/local/bin/crew:1916:in `<main>'
```
Reinstalling the same package without `-s` works fine.  Also, installing the dependency separately works fine.
```
$ crew install llvm18_dev
llvm18_dev: LLVM: Everything except libLLVM & llvm-strip
http://llvm.org/
Version: 18.1.5
License: Apache-2.0-with-LLVM-exceptions, UoI-NCSA, BSD, public-domain, rc, Apache-2.0 and MIT
Performing pre-flight checks...
Precompiled binary available, downloading...
Llvm18_dev archive downloaded.
Unpacking archive using 'tar', this may take a while...
Performing pre-install...
Performing install...
Using rdfind to convert duplicate files to hard links.
Now scanning ".", found 4602 files.
Now have 4602 files in total.
Removed 0 files due to nonunique device and inode.
Total size is 1818913491 bytes or 2 GiB
Removed 3213 files due to unique sizes from list. 1389 files left.
Now eliminating candidates based on first bytes: removed 1329 files from list. 60 files left.
Now eliminating candidates based on last bytes: removed 6 files from list. 54 files left.
Now eliminating candidates based on sha1 checksum: removed 0 files from list. 54 files left.
It seems like you have 54 files that are not unique
Totally, 395 MiB can be reduced.
Now making hard links.
Making 34 links.
Llvm18_dev installed!
```

**Comment by Zopolis4** [comment]
Also seems relevant...
![image](https://github.com/chromebrew/chromebrew/assets/64618338/36393824-d8d6-4517-a410-178455a57804)

**Comment by satmandu** [comment]
This is just some debugging...

Add this to the top of the `def unpack` function in `crew`:
```ruby
def unpack(meta)
  crewlog "meta[:filename]:#{meta[:filename]}"
  puts "meta[:filename] for #{@pkg.name} is #{meta[:filename]}".lightred
  puts "CREW_VERBOSE is #{CREW_VERBOSE}".lightred
```

Then do a `crew install -vs hollywood`.
_Note that `CREW_VERBOSE` is getting lost, but that's another bug..._

`libevent` gets installed as a dependency, but it is being considered a source dependency.
I see this: `meta[:filename] for libevent is libevent.git` when it should be what I get from doing a `crew install libevent`:
`meta[:filename] for libevent is libevent-2.2-64decd4-chromeos-x86_64.tar.zst` 

This leads to the wrong file being extracted, and that's part of the way to the root cause of the error:
```
Performing install...
/usr/local/lib64/ruby/3.3.0/fileutils.rb:1169:in `rename': No such file or directory @ rb_file_s_rename - (dlist, /usr/local/etc/crew/meta/libevent.directorylist) (Errno::ENOENT)
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:1169:in `block in mv'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:2469:in `block in fu_each_src_dest'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:2485:in `fu_each_src_dest0'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:2467:in `fu_each_src_dest'
        from /usr/local/lib64/ruby/3.3.0/fileutils.rb:1160:in `mv'
        from /usr/local/bin/crew:1050:in `block in install_package'
        from /usr/local/bin/crew:1045:in `chdir'
        from /usr/local/bin/crew:1045:in `install_package'
        from /usr/local/bin/crew:1278:in `install'
        from /usr/local/bin/crew:1211:in `block in resolve_dependencies'
        from /usr/local/bin/crew:1208:in `each'
        from /usr/local/bin/crew:1208:in `resolve_dependencies'
        from /usr/local/bin/crew:1091:in `resolve_dependencies_and_install'
        from /usr/local/bin/crew:1766:in `block in install_command'
        from /usr/local/bin/crew:1750:in `each'
        from /usr/local/bin/crew:1750:in `install_command'
        from /usr/local/bin/crew:1891:in `<main>'
```


Thoughts @Zopolis4 ?

**Comment by Zopolis4** [comment]
There seems to be a confusion between `crew install -s` (only install this package from source) and `crew install -S` (install this package and all dependencies from source), and that's probably causing the issue. Some part of the code is behaving correctly and expecting a binary, but another part thinks we're installing everything from source.

**Comment by satmandu** [comment]
I think that's part of it... Any idea on a fix?

Clearly `meta[:filename] ` is being set wrong with `crew install -s` for the dependency packages...

**Comment by Zopolis4** [comment]
I think its because `@opt_source` is set for the entire lifetime of the command, and `crew download` checks for `@opt_source` in order to decide whether to download from source or not. Off the top of my head, I'm not sure how to fix this while we still have this logic in `bin/crew`, because we can't easily isolate scope there.
